package io.github.up2jakarta.cii.ppf;

import io.github.up2jakarta.cii.ppf.adapters.LanguageCodeAdapter;
import io.github.up2jakarta.xml.clv.Agency;
import io.github.up2jakarta.xml.clv.CodeList;
import io.github.up2jakarta.xml.clv.Documented;
import io.github.up2jakarta.xml.clv.Schema;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import javax.annotation.processing.Generated;

/**
 * Based on ISO 639 : ISO 2 Alpha Language Code.
 */
@Generated(value = "PPF", comments = "by A.ABBESSI")
@Documented(value = "ISO 2 Alpha Language Code", agency = Agency.ISO, version = "2006-10-27")
@Schema(agency = "UN/CEFACT", version = "2.1", date = "2008-08-23")
@XmlJavaTypeAdapter(LanguageCodeAdapter.class)
public enum LanguageCodeType implements CodeList<LanguageCodeType> {

    AA("aa", "Afar"),
    AB("ab", "Abkhazian"),
    AE("ae", "Avestan"),
    AF("af", "Afrikaans"),
    AK("ak", "Akan"),
    AM("am", "Amharic"),
    AN("an", "Aragonese"),
    AR("ar", "Arabic"),
    AS("as", "Assamese"),
    AV("av", "Avaric"),
    AY("ay", "Aymara"),
    AZ("az", "Azerbaijani"),
    BA("ba", "Bashkir"),
    BE("be", "Belarusian"),
    BG("bg", "Bulgarian"),
    BH("bh", "Bihari"),
    BI("bi", "Bislama"),
    BM("bm", "Bambara"),
    BN("bn", "Bengali"),
    BO("bo", "Tibetan"),
    BR("br", "Breton"),
    BS("bs", "Bosnian"),
    CA("ca", "Catalan; Valencian"),
    CE("ce", "Chechen"),
    CH("ch", "Chamorro"),
    CO("co", "Corsican"),
    CR("cr", "Cree"),
    CS("cs", "Czech"),
    CU("cu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
    CV("cv", "Chuvash"),
    CY("cy", "Welsh"),
    DA("da", "Danish"),
    DE("de", "German"),
    DV("dv", "Divehi; Dhivehi; Maldivian"),
    DZ("dz", "Dzongkha"),
    EE("ee", "Ewe"),
    EL("el", "Greek; Modern (1453-)"),
    EN("en", "English"),
    EO("eo", "Esperanto"),
    ES("es", "Spanish; Castilian"),
    ET("et", "Estonian"),
    EU("eu", "Basque"),
    FA("fa", "Persian"),
    FF("ff", "Fulah"),
    FI("fi", "Finnish"),
    FJ("fj", "Fijian"),
    FO("fo", "Faroese"),
    FR("fr", "French"),
    FY("fy", "Western Frisian"),
    GA("ga", "Irish"),
    GD("gd", "Gaelic; Scottish Gaelic"),
    GL("gl", "Galician"),
    GN("gn", "Guarani"),
    GU("gu", "Gujarati"),
    GV("gv", "Manx"),
    HA("ha", "Hausa"),
    HE("he", "Hebrew"),
    HI("hi", "Hindi"),
    HO("ho", "Hiri Motu"),
    HR("hr", "Croatian"),
    HT("ht", "Haitian; Haitian Creole"),
    HU("hu", "Hungarian"),
    HY("hy", "Armenian"),
    HZ("hz", "Herero"),
    IA("ia", "Interlingua (International Auxiliary Language Association)"),
    ID("id", "Indonesian"),
    IE("ie", "Interlingue"),
    IG("ig", "Igbo"),
    II("ii", "Sichuan Yi"),
    IK("ik", "Inupiaq"),
    IO("io", "Ido"),
    IS("is", "Icelandic"),
    IT("it", "Italian"),
    IU("iu", "Inuktiut"),
    JA("ja", "Japanese"),
    JV("jv", "Javanese"),
    KA("ka", "Georgian"),
    KG("kg", "Kongo"),
    KI("ki", "Kikuyu; Gikuyu"),
    KJ("kj", "Kuanyama; Kwanyama"),
    KK("kk", "Kazakh"),
    KL("kl", "Kalaallisut; Greenlandic"),
    KM("km", "Central Khmer"),
    KN("kn", "Kannada"),
    KO("ko", "Korean"),
    KR("kr", "Kanuri"),
    KS("ks", "Kashmiri"),
    KU("ku", "Kurdish"),
    KV("kv", "Komi"),
    KW("kw", "Cornish"),
    KY("ky", "Kirghiz; Kyrgyz"),
    LA("la", "Latin"),
    LB("lb", "Luxembourgish; Letzeburgesch"),
    LG("lg", "Ganda"),
    LI("li", "Limburgan; Limburger; Limburgish"),
    LN("ln", "Lingala"),
    LO("lo", "Lao"),
    LT("lt", "Lithuanian"),
    LU("lu", "Luba-Katanga"),
    LV("lv", "Latvian"),
    MG("mg", "Malagasy"),
    MH("mh", "Marshallese"),
    MI("mi", "Maori"),
    MK("mk", "Macedonian"),
    ML("ml", "Malayalam"),
    MN("mn", "Mongolian"),
    MO("mo", "Moldavian; Moldovan"),
    MR("mr", "Marathi"),
    MS("ms", "Malay"),
    MT("mt", "Maltese"),
    MY("my", "Burmese"),
    NA("na", "Nauru"),
    NB("nb", "Bokmal Norwegian; Norwegian Bokmal"),
    ND("nd", "Ndebele; North; North Ndebele"),
    NE("ne", "Nepali"),
    NG("ng", "Ndonga"),
    NL("nl", "Dutch; Flemish"),
    NN("nn", "Norwegian Nynorsk; Nynorsk, Norwegian"),
    NO("no", "Norwegian"),
    NR("nr", "Ndebele; South; South Ndebele"),
    NV("nv", "Navajo; Navaho"),
    NY("ny", "Chichewa; Chewa; Nyanja"),
    OC("oc", "Occitan (post 1500); Provencal"),
    OJ("oj", "Ojibwa"),
    OM("om", "Oromo"),
    OR("or", "Oriya"),
    OS("os", "Ossetian; Ossetic"),
    PA("pa", "Panjabi; Punjabi"),
    PI("pi", "Pali"),
    PL("pl", "Polish"),
    PS("ps", "Pushto; Pashto"),
    PT("pt", "Portuguese"),
    QU("qu", "Quechua"),
    RM("rm", "Romansh"),
    RN("rn", "Rundi"),
    RO("ro", "Romanian"),
    RU("ru", "Russian"),
    RW("rw", "Kinyarwanda"),
    SA("sa", "Sanskrit"),
    SC("sc", "Sardinian"),
    SD("sd", "Sindhi"),
    SE("se", "Northern Sami"),
    SG("sg", "Sango"),
    SI("si", "Sinhala; Sinhalese"),
    SK("sk", "Slovak"),
    SL("sl", "Slovenian"),
    SM("sm", "Samoan"),
    SN("sn", "Shona"),
    SO("so", "Somali"),
    SQ("sq", "Albanian"),
    SR("sr", "Serbian"),
    SS("ss", "Swati"),
    ST("st", "Sotho, Southern"),
    SU("su", "Sundanese"),
    SV("sv", "Swedish"),
    SW("sw", "Swahili"),
    TA("ta", "Tamil"),
    TE("te", "Telugu"),
    TG("tg", "Tajik"),
    TH("th", "Thai"),
    TI("ti", "Tigrinya"),
    TK("tk", "Turkmen"),
    TL("tl", "Tagalog"),
    TN("tn", "Tswana"),
    TO("to", "Tonga (Tonga Islands)"),
    TR("tr", "Turkish"),
    TS("ts", "Tsonga"),
    TT("tt", "Tatar"),
    TW("tw", "Twi"),
    TY("ty", "Tahitian"),
    UG("ug", "Uighur; Uyghur"),
    UK("uk", "Ukrainian"),
    UR("ur", "Urdu"),
    UZ("uz", "Uzbek"),
    VE("ve", "Venda"),
    VI("vi", "Vietnamese"),
    VO("vo", "Volapük"),
    WA("wa", "Walloon"),
    WO("wo", "Wolof"),
    XH("xh", "Xhosa"),
    YI("yi", "Yiddish"),
    YO("yo", "Yoruba"),
    ZA("za", "Zhuang; Chuang"),
    ZH("zh", "Chinese"),
    ZU("zu", "Zulu"),
    ;

    private final String name;
    private final String code;

    LanguageCodeType(String code, String name) {
        this.code = code;
        this.name = name;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public String getCode() {
        return code;
    }

}
