package io.github.up2jakarta.cii.ppf;

import io.github.up2jakarta.cii.ppf.adapters.MeasurementUnitCodeAdapter;
import io.github.up2jakarta.xml.codelist.Agency;
import io.github.up2jakarta.xml.codelist.CodeList;
import io.github.up2jakarta.xml.codelist.Documented;
import io.github.up2jakarta.xml.codelist.Schema;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import javax.annotation.processing.Generated;

/**
 * Based on UN/CEFACT R20 : Measurement Unit Common Code.
 * {@see https://unece.org/trade/uncefact/cl-recommendations}
 */
@Generated(value = "PPF", comments = "by A.ABBESSI")
@Documented(value = "Measurement Unit Common Code", agency = Agency.UN_ECE, version = "4")
@Schema(agency = "UN/CEFACT", version = "1.1", date = "2008-08-23")
@XmlJavaTypeAdapter(MeasurementUnitCodeAdapter.class)
public enum MeasurementUnitCode implements CodeList<MeasurementUnitCode> {

    V_5J("5J", "Hydraulic horse power"),
    V_5E("5E", "MMSCF/day"),
    V_5B("5B", "Batch"),
    V_5A("5A", "Barrel (US) per minute"),
    V_4X("4X", "Kilolitre per hour"),
    V_4W("4W", "Ton (US) per hour"),
    V_4U("4U", "Pound per hour"),
    V_4T("4T", "Picofarad"),
    V_4R("4R", "Ounce foot"),
    V_4Q("4Q", "Ounce inch"),
    V_4P("4P", "Newton per metre"),
    V_4O("4O", "Microfarad"),
    V_4N("4N", "Megabecquerel"),
    V_4M("4M", "Milligram per hour"),
    V_4L("4L", "Megabyte"),
    V_4K("4K", "Milliampere"),
    V_4H("4H", "Micrometre (micron)"),
    V_4G("4G", "Microlitre"),
    V_4C("4C", "Centistokes"),
    V_3C("3C", "Manmonth"),
    V_3B("3B", "Megajoule"),
    V_2Z("2Z", "Millivolt"),
    V_2Y("2Y", "Milliroentgen"),
    V_2X("2X", "Metre per minute"),
    V_2U("2U", "Megagram"),
    V_2R("2R", "Kilocurie"),
    V_2Q("2Q", "Kilobecquerel"),
    V_2P("2P", "Kilobyte"),
    V_2N("2N", "Decibel"),
    V_2M("2M", "Centimetre per second"),
    V_2L("2L", "Cubic foot per minute"),
    V_2K("2K", "Cubic foot per hour"),
    V_2J("2J", "Cubic centimetre per second"),
    V_2I("2I", "British thermal unit (international table) per hour"),
    V_2H("2H", "Volt DC"),
    V_2G("2G", "Volt AC"),
    V_2C("2C", "Roentgen"),
    V_2B("2B", "Radian per second squared"),
    V_2A("2A", "Radian per second"),
    V_1I("1I", "Fixed rate"),
    V_10("10", "Group"),
    V_11("11", "Outfit"),
    V_13("13", "Ration"),
    V_14("14", "Shot"),
    V_15("15", "Stick, military"),
    V_20("20", "Twenty foot container"),
    V_21("21", "Forty foot container"),
    V_22("22", "Decilitre per gram"),
    V_23("23", "Gram per cubic centimetre"),
    V_24("24", "Theoretical pound"),
    V_25("25", "Gram per square centimetre"),
    V_27("27", "Theoretical ton"),
    V_28("28", "Kilogram per square metre"),
    V_33("33", "Kilopascal square metre per gram"),
    V_34("34", "Kilopascal per millimetre"),
    V_35("35", "Millilitre per square centimetre second"),
    V_37("37", "Ounce per square foot"),
    V_38("38", "Ounce per square foot per 0,01inch"),
    V_40("40", "Millilitre per second"),
    V_41("41", "Millilitre per minute"),
    V_56("56", "Sitas"),
    V_57("57", "Mesh"),
    V_58("58", "Net kilogram"),
    V_59("59", "Part per million"),
    V_60("60", "Percent weight"),
    V_61("61", "Part per billion (US)"),
    V_74("74", "Millipascal"),
    V_77("77", "Milli-inch"),
    V_80("80", "Pound per square inch absolute"),
    V_81("81", "Henry"),
    V_85("85", "Foot pound-force"),
    V_87("87", "Pound per cubic foot"),
    V_89("89", "Poise"),
    V_91("91", "Stokes"),
    A10("A10", "Ampere square metre per joule second"),
    A11("A11", "Angstrom"),
    A12("A12", "Astronomical unit"),
    A13("A13", "Attojoule"),
    A14("A14", "Barn"),
    A15("A15", "Barn per electronvolt"),
    A16("A16", "Barn per steradian electronvolt"),
    A17("A17", "Barn per steradian"),
    A18("A18", "Becquerel per kilogram"),
    A19("A19", "Becquerel per cubic metre"),
    A2("A2", "Ampere per centimetre"),
    A20("A20", "British thermal unit (international table) per second square foot degree Rankine"),
    A21("A21", "British thermal unit (international table) per pound degree Rankine"),
    A22("A22", "British thermal unit (international table) per second foot degree Rankine"),
    A23("A23", "British thermal unit (international table) per hour square foot degree Rankine"),
    A24("A24", "Candela per square metre"),
    A26("A26", "Coulomb metre"),
    A27("A27", "Coulomb metre squared per volt"),
    A28("A28", "Coulomb per cubic centimetre"),
    A29("A29", "Coulomb per cubic metre"),
    A3("A3", "Ampere per millimetre"),
    A30("A30", "Coulomb per cubic millimetre"),
    A31("A31", "Coulomb per kilogram second"),
    A32("A32", "Coulomb per mole"),
    A33("A33", "Coulomb per square centimetre"),
    A34("A34", "Coulomb per square metre"),
    A35("A35", "Coulomb per square millimetre"),
    A36("A36", "Cubic centimetre per mole"),
    A37("A37", "Cubic decimetre per mole"),
    A38("A38", "Cubic metre per coulomb"),
    A39("A39", "Cubic metre per kilogram"),
    A4("A4", "Ampere per square centimetre"),
    A40("A40", "Cubic metre per mole"),
    A41("A41", "Ampere per square metre"),
    A42("A42", "Curie per kilogram"),
    A43("A43", "Deadweight tonnage"),
    A44("A44", "Decalitre"),
    A45("A45", "Decametre"),
    A47("A47", "Decitex"),
    A48("A48", "Degree Rankine"),
    A49("A49", "Denier"),
    A5("A5", "Ampere square metre"),
    A53("A53", "Electronvolt"),
    A54("A54", "Electronvolt per metre"),
    A55("A55", "Electronvolt square metre"),
    A56("A56", "Electronvolt square metre per kilogram"),
    A59("A59", "8-part cloud cover"),
    A6("A6", "Ampere per square metre kelvin squared"),
    A68("A68", "Exajoule"),
    A69("A69", "Farad per metre"),
    A7("A7", "Ampere per square millimetre"),
    A70("A70", "Femtojoule"),
    A71("A71", "Femtometre"),
    A73("A73", "Foot per second squared"),
    A74("A74", "Foot pound-force per second"),
    A75("A75", "Freight ton"),
    A76("A76", "Gal"),
    A8("A8", "Ampere second"),
    A84("A84", "Gigacoulomb per cubic metre"),
    A85("A85", "Gigaelectronvolt"),
    A86("A86", "Gigahertz"),
    A87("A87", "Gigaohm"),
    A88("A88", "Gigaohm metre"),
    A89("A89", "Gigapascal"),
    A9("A9", "Rate"),
    A90("A90", "Gigawatt"),
    A91("A91", "Gon"),
    A93("A93", "Gram per cubic metre"),
    A94("A94", "Gram per mole"),
    A95("A95", "Gray"),
    A96("A96", "Gray per second"),
    A97("A97", "Hectopascal"),
    A98("A98", "Henry per metre"),
    A99("A99", "Bit"),
    AA("AA", "Ball"),
    AB("AB", "Bulk pack"),
    ACR("ACR", "Acre"),
    ACT("ACT", "Activity"),
    AD("AD", "Byte"),
    AE("AE", "Ampere per metre"),
    AH("AH", "Additional minute"),
    AI("AI", "Average minute per call"),
    AK("AK", "Fathom"),
    AL("AL", "Access line"),
    AMH("AMH", "Ampere hour"),
    AMP("AMP", "Ampere"),
    ANN("ANN", "Year"),
    APZ("APZ", "Troy ounce or apothecary ounce"),
    AQ("AQ", "Anti-hemophilic factor (AHF) unit"),
    AS("AS", "Assortment"),
    ASM("ASM", "Alcoholic strength by mass"),
    ASU("ASU", "Alcoholic strength by volume"),
    ATM("ATM", "Standard atmosphere"),
    AWG("AWG", "American wire gauge"),
    AY("AY", "Assembly"),
    AZ("AZ", "British thermal unit (international table) per pound"),
    B1("B1", "Barrel (US) per day"),
    B10("B10", "Bit per second"),
    B11("B11", "Joule per kilogram kelvin"),
    B12("B12", "Joule per metre"),
    B13("B13", "Joule per square metre"),
    B14("B14", "Joule per metre to the fourth power"),
    B15("B15", "Joule per mole"),
    B16("B16", "Joule per mole kelvin"),
    B17("B17", "Credit"),
    B18("B18", "Joule second"),
    B19("B19", "Digit"),
    B20("B20", "Joule square metre per kilogram"),
    B21("B21", "Kelvin per watt"),
    B22("B22", "Kiloampere"),
    B23("B23", "Kiloampere per square metre"),
    B24("B24", "Kiloampere per metre"),
    B25("B25", "Kilobecquerel per kilogram"),
    B26("B26", "Kilocoulomb"),
    B27("B27", "Kilocoulomb per cubic metre"),
    B28("B28", "Kilocoulomb per square metre"),
    B29("B29", "Kiloelectronvolt"),
    B3("B3", "Batting pound"),
    B30("B30", "Gibibit"),
    B31("B31", "Kilogram metre per second"),
    B32("B32", "Kilogram metre squared"),
    B33("B33", "Kilogram metre squared per second"),
    B34("B34", "Kilogram per cubic decimetre"),
    B35("B35", "Kilogram per litre"),
    B4("B4", "Barrel, imperial"),
    B41("B41", "Kilojoule per kelvin"),
    B42("B42", "Kilojoule per kilogram"),
    B43("B43", "Kilojoule per kilogram kelvin"),
    B44("B44", "Kilojoule per mole"),
    B45("B45", "Kilomole"),
    B46("B46", "Kilomole per cubic metre"),
    B47("B47", "Kilonewton"),
    B48("B48", "Kilonewton metre"),
    B49("B49", "Kiloohm"),
    B50("B50", "Kiloohm metre"),
    B52("B52", "Kilosecond"),
    B53("B53", "Kilosiemens"),
    B54("B54", "Kilosiemens per metre"),
    B55("B55", "Kilovolt per metre"),
    B56("B56", "Kiloweber per metre"),
    B57("B57", "Light year"),
    B58("B58", "Litre per mole"),
    B59("B59", "Lumen hour"),
    B60("B60", "Lumen per square metre"),
    B61("B61", "Lumen per watt"),
    B62("B62", "Lumen second"),
    B63("B63", "Lux hour"),
    B64("B64", "Lux second"),
    B66("B66", "Megaampere per square metre"),
    B67("B67", "Megabecquerel per kilogram"),
    B68("B68", "Gigabit"),
    B69("B69", "Megacoulomb per cubic metre"),
    B7("B7", "Cycle"),
    B70("B70", "Megacoulomb per square metre"),
    B71("B71", "Megaelectronvolt"),
    B72("B72", "Megagram per cubic metre"),
    B73("B73", "Meganewton"),
    B74("B74", "Meganewton metre"),
    B75("B75", "Megaohm"),
    B76("B76", "Megaohm metre"),
    B77("B77", "Megasiemens per metre"),
    B78("B78", "Megavolt"),
    B79("B79", "Megavolt per metre"),
    B8("B8", "Joule per cubic metre"),
    B80("B80", "Gigabit per second"),
    B81("B81", "Reciprocal metre squared reciprocal second"),
    B82("B82", "Inch per linear foot"),
    B83("B83", "Metre to the fourth power"),
    B84("B84", "Microampere"),
    B85("B85", "Microbar"),
    B86("B86", "Microcoulomb"),
    B87("B87", "Microcoulomb per cubic metre"),
    B88("B88", "Microcoulomb per square metre"),
    B89("B89", "Microfarad per metre"),
    B90("B90", "Microhenry"),
    B91("B91", "Microhenry per metre"),
    B92("B92", "Micronewton"),
    B93("B93", "Micronewton metre"),
    B94("B94", "Microohm"),
    B95("B95", "Microohm metre"),
    B96("B96", "Micropascal"),
    B97("B97", "Microradian"),
    B98("B98", "Microsecond"),
    B99("B99", "Microsiemens"),
    BAR("BAR", "Bar [unit of pressure]"),
    BB("BB", "Base box"),
    BFT("BFT", "Board foot"),
    BHP("BHP", "Brake horse power"),
    BIL("BIL", "Billion (EUR)"),
    BLD("BLD", "Dry barrel (US)"),
    BLL("BLL", "Barrel (US)"),
    BP("BP", "Hundred board foot"),
    BPM("BPM", "Beats per minute"),
    BQL("BQL", "Becquerel"),
    BTU("BTU", "British thermal unit (international table)"),
    BUA("BUA", "Bushel (US)"),
    BUI("BUI", "Bushel (UK)"),
    C0("C0", "Call"),
    C10("C10", "Millifarad"),
    C11("C11", "Milligal"),
    C12("C12", "Milligram per metre"),
    C13("C13", "Milligray"),
    C14("C14", "Millihenry"),
    C15("C15", "Millijoule"),
    C16("C16", "Millimetre per second"),
    C17("C17", "Millimetre squared per second"),
    C18("C18", "Millimole"),
    C19("C19", "Mole per kilogram"),
    C20("C20", "Millinewton"),
    C21("C21", "Kibibit"),
    C22("C22", "Millinewton per metre"),
    C23("C23", "Milliohm metre"),
    C24("C24", "Millipascal second"),
    C25("C25", "Milliradian"),
    C26("C26", "Millisecond"),
    C27("C27", "Millisiemens"),
    C28("C28", "Millisievert"),
    C29("C29", "Millitesla"),
    C3("C3", "Microvolt per metre"),
    C30("C30", "Millivolt per metre"),
    C31("C31", "Milliwatt"),
    C32("C32", "Milliwatt per square metre"),
    C33("C33", "Milliweber"),
    C34("C34", "Mole"),
    C35("C35", "Mole per cubic decimetre"),
    C36("C36", "Mole per cubic metre"),
    C37("C37", "Kilobit"),
    C38("C38", "Mole per litre"),
    C39("C39", "Nanoampere"),
    C40("C40", "Nanocoulomb"),
    C41("C41", "Nanofarad"),
    C42("C42", "Nanofarad per metre"),
    C43("C43", "Nanohenry"),
    C44("C44", "Nanohenry per metre"),
    C45("C45", "Nanometre"),
    C46("C46", "Nanoohm metre"),
    C47("C47", "Nanosecond"),
    C48("C48", "Nanotesla"),
    C49("C49", "Nanowatt"),
    C50("C50", "Neper"),
    C51("C51", "Neper per second"),
    C52("C52", "Picometre"),
    C53("C53", "Newton metre second"),
    C54("C54", "Newton metre squared per kilogram squared"),
    C55("C55", "Newton per square metre"),
    C56("C56", "Newton per square millimetre"),
    C57("C57", "Newton second"),
    C58("C58", "Newton second per metre"),
    C59("C59", "Octave"),
    C60("C60", "Ohm centimetre"),
    C61("C61", "Ohm metre"),
    C62("C62", "One"),
    C63("C63", "Parsec"),
    C64("C64", "Pascal per kelvin"),
    C65("C65", "Pascal second"),
    C66("C66", "Pascal second per cubic metre"),
    C67("C67", "Pascal second per metre"),
    C68("C68", "Petajoule"),
    C69("C69", "Phon"),
    C7("C7", "Centipoise"),
    C70("C70", "Picoampere"),
    C71("C71", "Picocoulomb"),
    C72("C72", "Picofarad per metre"),
    C73("C73", "Picohenry"),
    C74("C74", "Kilobit per second"),
    C75("C75", "Picowatt"),
    C76("C76", "Picowatt per square metre"),
    C78("C78", "Pound-force"),
    C79("C79", "Kilovolt ampere hour"),
    C8("C8", "Millicoulomb per kilogram"),
    C80("C80", "Rad"),
    C81("C81", "Radian"),
    C82("C82", "Radian square metre per mole"),
    C83("C83", "Radian square metre per kilogram"),
    C84("C84", "Radian per metre"),
    C85("C85", "Reciprocal angstrom"),
    C86("C86", "Reciprocal cubic metre"),
    C87("C87", "Reciprocal cubic metre per second"),
    C88("C88", "Reciprocal electron volt per cubic metre"),
    C89("C89", "Reciprocal henry"),
    C9("C9", "Coil group"),
    C90("C90", "Reciprocal joule per cubic metre"),
    C91("C91", "Reciprocal kelvin or kelvin to the power minus one"),
    C92("C92", "Reciprocal metre"),
    C93("C93", "Reciprocal square metre"),
    C94("C94", "Reciprocal minute"),
    C95("C95", "Reciprocal mole"),
    C96("C96", "Reciprocal pascal or pascal to the power minus one"),
    C97("C97", "Reciprocal second"),
    C99("C99", "Reciprocal second per metre squared"),
    CCT("CCT", "Carrying capacity in metric ton"),
    CDL("CDL", "Candela"),
    CEL("CEL", "Degree Celsius"),
    CEN("CEN", "Hundred"),
    CG("CG", "Card"),
    CGM("CGM", "Centigram"),
    CKG("CKG", "Coulomb per kilogram"),
    CLF("CLF", "Hundred leave"),
    CLT("CLT", "Centilitre"),
    CMK("CMK", "Square centimetre"),
    CMQ("CMQ", "Cubic centimetre"),
    CMT("CMT", "Centimetre"),
    CNP("CNP", "Hundred pack"),
    CNT("CNT", "Cental (UK)"),
    COU("COU", "Coulomb"),
    CTG("CTG", "Content gram"),
    CTM("CTM", "Metric carat"),
    CTN("CTN", "Content ton (metric)"),
    CUR("CUR", "Curie"),
    CWA("CWA", "Hundred pound (cwt) / hundred weight (US)"),
    CWI("CWI", "Hundred weight (UK)"),
    D03("D03", "Kilowatt hour per hour"),
    D04("D04", "Lot  [unit of weight]"),
    D1("D1", "Reciprocal second per steradian"),
    D10("D10", "Siemens per metre"),
    D11("D11", "Mebibit"),
    D12("D12", "Siemens square metre per mole"),
    D13("D13", "Sievert"),
    D15("D15", "Sone"),
    D16("D16", "Square centimetre per erg"),
    D17("D17", "Square centimetre per steradian erg"),
    D18("D18", "Metre kelvin"),
    D19("D19", "Square metre kelvin per watt"),
    D2("D2", "Reciprocal second per steradian metre squared"),
    D20("D20", "Square metre per joule"),
    D21("D21", "Square metre per kilogram"),
    D22("D22", "Square metre per mole"),
    D23("D23", "Pen gram (protein)"),
    D24("D24", "Square metre per steradian"),
    D25("D25", "Square metre per steradian joule"),
    D26("D26", "Square metre per volt second"),
    D27("D27", "Steradian"),
    D29("D29", "Terahertz"),
    D30("D30", "Terajoule"),
    D31("D31", "Terawatt"),
    D32("D32", "Terawatt hour"),
    D33("D33", "Tesla"),
    D34("D34", "Tex"),
    D36("D36", "Megabit"),
    D41("D41", "Tonne per cubic metre"),
    D42("D42", "Tropical year"),
    D43("D43", "Unified atomic mass unit"),
    D44("D44", "Var"),
    D45("D45", "Volt squared per kelvin squared"),
    D46("D46", "Volt - ampere"),
    D47("D47", "Volt per centimetre"),
    D48("D48", "Volt per kelvin"),
    D49("D49", "Millivolt per kelvin"),
    D5("D5", "Kilogram per square centimetre"),
    D50("D50", "Volt per metre"),
    D51("D51", "Volt per millimetre"),
    D52("D52", "Watt per kelvin"),
    D53("D53", "Watt per metre kelvin"),
    D54("D54", "Watt per square metre"),
    D55("D55", "Watt per square metre kelvin"),
    D56("D56", "Watt per square metre kelvin to the fourth power"),
    D57("D57", "Watt per steradian"),
    D58("D58", "Watt per steradian square metre"),
    D59("D59", "Weber per metre"),
    D6("D6", "Roentgen per second"),
    D60("D60", "Weber per millimetre"),
    D61("D61", "Minute [unit of angle]"),
    D62("D62", "Second [unit of angle]"),
    D63("D63", "Book"),
    D65("D65", "Round"),
    D68("D68", "Number of words"),
    D69("D69", "Inch to the fourth power"),
    D73("D73", "Joule square metre"),
    D74("D74", "Kilogram per mole"),
    D77("D77", "Megacoulomb"),
    D78("D78", "Megajoule per second"),
    D80("D80", "Microwatt"),
    D81("D81", "Microtesla"),
    D82("D82", "Microvolt"),
    D83("D83", "Millinewton metre"),
    D85("D85", "Microwatt per square metre"),
    D86("D86", "Millicoulomb"),
    D87("D87", "Millimole per kilogram"),
    D88("D88", "Millicoulomb per cubic metre"),
    D89("D89", "Millicoulomb per square metre"),
    D91("D91", "Rem"),
    D93("D93", "Second per cubic metre"),
    D94("D94", "Second per cubic metre radian"),
    D95("D95", "Joule per gram"),
    DAA("DAA", "Decare"),
    DAD("DAD", "Ten day"),
    DAY("DAY", "Day"),
    DB("DB", "Dry pound"),
    DD("DD", "Degree [unit of angle]"),
    DEC("DEC", "Decade"),
    DG("DG", "Decigram"),
    DJ("DJ", "Decagram"),
    DLT("DLT", "Decilitre"),
    DMA("DMA", "Cubic decametre"),
    DMK("DMK", "Square decimetre"),
    DMO("DMO", "Standard kilolitre"),
    DMQ("DMQ", "Cubic decimetre"),
    DMT("DMT", "Decimetre"),
    DN("DN", "Decinewton metre"),
    DPC("DPC", "Dozen piece"),
    DPR("DPR", "Dozen pair"),
    DPT("DPT", "Displacement tonnage"),
    DRA("DRA", "Dram (US)"),
    DRI("DRI", "Dram (UK)"),
    DRL("DRL", "Dozen roll"),
    DT("DT", "Dry ton"),
    DTN("DTN", "Decitonne"),
    DWT("DWT", "Pennyweight"),
    DZN("DZN", "Dozen"),
    DZP("DZP", "Dozen pack"),
    E01("E01", "Newton per square centimetre"),
    E07("E07", "Megawatt hour per hour"),
    E08("E08", "Megawatt per hertz"),
    E09("E09", "Milliampere hour"),
    E10("E10", "Degree day"),
    E12("E12", "Mille"),
    E14("E14", "Kilocalorie (international table)"),
    E15("E15", "Kilocalorie (thermochemical) per hour"),
    E16("E16", "Million Btu(IT) per hour"),
    E17("E17", "Cubic foot per second"),
    E18("E18", "Tonne per hour"),
    E19("E19", "Ping"),
    E20("E20", "Megabit per second"),
    E21("E21", "Shares"),
    E22("E22", "TEU"),
    E23("E23", "Tyre"),
    E25("E25", "Active unit"),
    E27("E27", "Dose"),
    E28("E28", "Air dry ton"),
    E30("E30", "Strand"),
    E31("E31", "Square metre per litre"),
    E32("E32", "Litre per hour"),
    E33("E33", "Foot per thousand"),
    E34("E34", "Gigabyte"),
    E35("E35", "Terabyte"),
    E36("E36", "Petabyte"),
    E37("E37", "Pixel"),
    E38("E38", "Megapixel"),
    E39("E39", "Dots per inch"),
    E4("E4", "Gross kilogram"),
    E40("E40", "Part per hundred thousand"),
    E41("E41", "Kilogram-force per square millimetre"),
    E42("E42", "Kilogram-force per square centimetre"),
    E43("E43", "Joule per square centimetre"),
    E44("E44", "Kilogram-force metre per square centimetre"),
    E45("E45", "Milliohm"),
    E46("E46", "Kilowatt hour per cubic metre"),
    E47("E47", "Kilowatt hour per kelvin"),
    E48("E48", "Service unit"),
    E49("E49", "Working day"),
    E50("E50", "Accounting unit"),
    E51("E51", "Job"),
    E52("E52", "Run foot"),
    E53("E53", "Test"),
    E54("E54", "Trip"),
    E55("E55", "Use"),
    E56("E56", "Well"),
    E57("E57", "Zone"),
    E58("E58", "Exabit per second"),
    E59("E59", "Exbibyte"),
    E60("E60", "Pebibyte"),
    E61("E61", "Tebibyte"),
    E62("E62", "Gibibyte"),
    E63("E63", "Mebibyte"),
    E64("E64", "Kibibyte"),
    E65("E65", "Exbibit per metre"),
    E66("E66", "Exbibit per square metre"),
    E67("E67", "Exbibit per cubic metre"),
    E68("E68", "Gigabyte per second"),
    E69("E69", "Gibibit per metre"),
    E70("E70", "Gibibit per square metre"),
    E71("E71", "Gibibit per cubic metre"),
    E72("E72", "Kibibit per metre"),
    E73("E73", "Kibibit per square metre"),
    E74("E74", "Kibibit per cubic metre"),
    E75("E75", "Mebibit per metre"),
    E76("E76", "Mebibit per square metre"),
    E77("E77", "Mebibit per cubic metre"),
    E78("E78", "Petabit"),
    E79("E79", "Petabit per second"),
    E80("E80", "Pebibit per metre"),
    E81("E81", "Pebibit per square metre"),
    E82("E82", "Pebibit per cubic metre"),
    E83("E83", "Terabit"),
    E84("E84", "Terabit per second"),
    E85("E85", "Tebibit per metre"),
    E86("E86", "Tebibit per cubic metre"),
    E87("E87", "Tebibit per square metre"),
    E88("E88", "Bit per metre"),
    E89("E89", "Bit per square metre"),
    E90("E90", "Reciprocal centimetre"),
    E91("E91", "Reciprocal day"),
    E92("E92", "Cubic decimetre per hour"),
    E93("E93", "Kilogram per hour"),
    E94("E94", "Kilomole per second"),
    E95("E95", "Mole per second"),
    E96("E96", "Degree per second"),
    E97("E97", "Millimetre per degree Celcius metre"),
    E98("E98", "Degree Celsius per kelvin"),
    E99("E99", "Hectopascal per bar"),
    EA("EA", "Each"),
    EB("EB", "Electronic mail box"),
    EQ("EQ", "Equivalent gallon"),
    F01("F01", "Bit per cubic metre"),
    F02("F02", "Kelvin per kelvin"),
    F03("F03", "Kilopascal per bar"),
    F04("F04", "Millibar per bar"),
    F05("F05", "Megapascal per bar"),
    F06("F06", "Poise per bar"),
    F07("F07", "Pascal per bar"),
    F08("F08", "Milliampere per inch"),
    F10("F10", "Kelvin per hour"),
    F11("F11", "Kelvin per minute"),
    F12("F12", "Kelvin per second"),
    F13("F13", "Slug"),
    F14("F14", "Gram per kelvin"),
    F15("F15", "Kilogram per kelvin"),
    F16("F16", "Milligram per kelvin"),
    F17("F17", "Pound-force per foot"),
    F18("F18", "Kilogram square centimetre"),
    F19("F19", "Kilogram square millimetre"),
    F20("F20", "Pound inch squared"),
    F21("F21", "Pound-force inch"),
    F22("F22", "Pound-force foot per ampere"),
    F23("F23", "Gram per cubic decimetre"),
    F24("F24", "Kilogram per kilomol"),
    F25("F25", "Gram per hertz"),
    F26("F26", "Gram per day"),
    F27("F27", "Gram per hour"),
    F28("F28", "Gram per minute"),
    F29("F29", "Gram per second"),
    F30("F30", "Kilogram per day"),
    F31("F31", "Kilogram per minute"),
    F32("F32", "Milligram per day"),
    F33("F33", "Milligram per minute"),
    F34("F34", "Milligram per second"),
    F35("F35", "Gram per day kelvin"),
    F36("F36", "Gram per hour kelvin"),
    F37("F37", "Gram per minute kelvin"),
    F38("F38", "Gram per second kelvin"),
    F39("F39", "Kilogram per day kelvin"),
    F40("F40", "Kilogram per hour kelvin"),
    F41("F41", "Kilogram per minute kelvin"),
    F42("F42", "Kilogram per second kelvin"),
    F43("F43", "Milligram per day kelvin"),
    F44("F44", "Milligram per hour kelvin"),
    F45("F45", "Milligram per minute kelvin"),
    F46("F46", "Milligram per second kelvin"),
    F47("F47", "Newton per millimetre"),
    F48("F48", "Pound-force per inch"),
    F49("F49", "Rod [unit of distance]"),
    F50("F50", "Micrometre per kelvin"),
    F51("F51", "Centimetre per kelvin"),
    F52("F52", "Metre per kelvin"),
    F53("F53", "Millimetre per kelvin"),
    F54("F54", "Milliohm per metre"),
    F55("F55", "Ohm per mile (statute mile)"),
    F56("F56", "Ohm per kilometre"),
    F57("F57", "Milliampere per pound-force per square inch"),
    F58("F58", "Reciprocal bar"),
    F59("F59", "Milliampere per bar"),
    F60("F60", "Degree Celsius per bar"),
    F61("F61", "Kelvin per bar"),
    F62("F62", "Gram per day bar"),
    F63("F63", "Gram per hour bar"),
    F64("F64", "Gram per minute bar"),
    F65("F65", "Gram per second bar"),
    F66("F66", "Kilogram per day bar"),
    F67("F67", "Kilogram per hour bar"),
    F68("F68", "Kilogram per minute bar"),
    F69("F69", "Kilogram per second bar"),
    F70("F70", "Milligram per day bar"),
    F71("F71", "Milligram per hour bar"),
    F72("F72", "Milligram per minute bar"),
    F73("F73", "Milligram per second bar"),
    F74("F74", "Gram per bar"),
    F75("F75", "Milligram per bar"),
    F76("F76", "Milliampere per millimetre"),
    F77("F77", "Pascal second per kelvin"),
    F78("F78", "Inch of water"),
    F79("F79", "Inch of mercury"),
    F80("F80", "Water horse power"),
    F81("F81", "Bar per kelvin"),
    F82("F82", "Hectopascal per kelvin"),
    F83("F83", "Kilopascal per kelvin"),
    F84("F84", "Millibar per kelvin"),
    F85("F85", "Megapascal per kelvin"),
    F86("F86", "Poise per kelvin"),
    F87("F87", "Volt per litre minute"),
    F88("F88", "Newton centimetre"),
    F89("F89", "Newton metre per degree"),
    F90("F90", "Newton metre per ampere"),
    F91("F91", "Bar litre per second"),
    F92("F92", "Bar cubic metre per second"),
    F93("F93", "Hectopascal litre per second"),
    F94("F94", "Hectopascal cubic metre per second"),
    F95("F95", "Millibar litre per second"),
    F96("F96", "Millibar cubic metre per second"),
    F97("F97", "Megapascal litre per second"),
    F98("F98", "Megapascal cubic metre per second"),
    F99("F99", "Pascal litre per second"),
    FAH("FAH", "Degree Fahrenheit"),
    FAR("FAR", "Farad"),
    FBM("FBM", "Fibre metre"),
    FC("FC", "Thousand cubic foot"),
    FF("FF", "Hundred cubic metre"),
    FH("FH", "Micromole"),
    FIT("FIT", "Failures in time"),
    FL("FL", "Flake ton"),
    FOT("FOT", "Foot"),
    FP("FP", "Pound per square foot"),
    FR("FR", "Foot per minute"),
    FS("FS", "Foot per second"),
    FTK("FTK", "Square foot"),
    FTQ("FTQ", "Cubic foot"),
    G01("G01", "Pascal cubic metre per second"),
    G04("G04", "Centimetre per bar"),
    G05("G05", "Metre per bar"),
    G06("G06", "Millimetre per bar"),
    G08("G08", "Square inch per second"),
    G09("G09", "Square metre per second kelvin"),
    G10("G10", "Stokes per kelvin"),
    G11("G11", "Gram per cubic centimetre bar"),
    G12("G12", "Gram per cubic decimetre bar"),
    G13("G13", "Gram per litre bar"),
    G14("G14", "Gram per cubic metre bar"),
    G15("G15", "Gram per millilitre bar"),
    G16("G16", "Kilogram per cubic centimetre bar"),
    G17("G17", "Kilogram per litre bar"),
    G18("G18", "Kilogram per cubic metre bar"),
    G19("G19", "Newton metre per kilogram"),
    G2("G2", "US gallon per minute"),
    G20("G20", "Pound-force foot per pound"),
    G21("G21", "Cup [unit of volume]"),
    G23("G23", "Peck"),
    G24("G24", "Tablespoon (US)"),
    G25("G25", "Teaspoon (US)"),
    G26("G26", "Stere"),
    G27("G27", "Cubic centimetre per kelvin"),
    G28("G28", "Litre per kelvin"),
    G29("G29", "Cubic metre per kelvin"),
    G3("G3", "Imperial gallon per minute"),
    G30("G30", "Millilitre per kelvin"),
    G31("G31", "Kilogram per cubic centimetre"),
    G32("G32", "Ounce (avoirdupois) per cubic yard"),
    G33("G33", "Gram per cubic centimetre kelvin"),
    G34("G34", "Gram per cubic decimetre kelvin"),
    G35("G35", "Gram per litre kelvin"),
    G36("G36", "Gram per cubic metre kelvin"),
    G37("G37", "Gram per millilitre kelvin"),
    G38("G38", "Kilogram per cubic centimetre kelvin"),
    G39("G39", "Kilogram per litre kelvin"),
    G40("G40", "Kilogram per cubic metre kelvin"),
    G41("G41", "Square metre per second bar"),
    G42("G42", "Microsiemens per centimetre"),
    G43("G43", "Microsiemens per metre"),
    G44("G44", "Nanosiemens per centimetre"),
    G45("G45", "Nanosiemens per metre"),
    G46("G46", "Stokes per bar"),
    G47("G47", "Cubic centimetre per day"),
    G48("G48", "Cubic centimetre per hour"),
    G49("G49", "Cubic centimetre per minute"),
    G50("G50", "Gallon (US) per hour"),
    G51("G51", "Litre per second"),
    G52("G52", "Cubic metre per day"),
    G53("G53", "Cubic metre per minute"),
    G54("G54", "Millilitre per day"),
    G55("G55", "Millilitre per hour"),
    G56("G56", "Cubic inch per hour"),
    G57("G57", "Cubic inch per minute"),
    G58("G58", "Cubic inch per second"),
    G59("G59", "Milliampere per litre minute"),
    G60("G60", "Volt per bar"),
    G61("G61", "Cubic centimetre per day kelvin"),
    G62("G62", "Cubic centimetre per hour kelvin"),
    G63("G63", "Cubic centimetre per minute kelvin"),
    G64("G64", "Cubic centimetre per second kelvin"),
    G65("G65", "Litre per day kelvin"),
    G66("G66", "Litre per hour kelvin"),
    G67("G67", "Litre per minute kelvin"),
    G68("G68", "Litre per second kelvin"),
    G69("G69", "Cubic metre per day kelvin"),
    G70("G70", "Cubic metre per hour kelvin"),
    G71("G71", "Cubic metre per minute kelvin"),
    G72("G72", "Cubic metre per second kelvin"),
    G73("G73", "Millilitre per day kelvin"),
    G74("G74", "Millilitre per hour kelvin"),
    G75("G75", "Millilitre per minute kelvin"),
    G76("G76", "Millilitre per second kelvin"),
    G77("G77", "Millimetre to the fourth power"),
    G78("G78", "Cubic centimetre per day bar"),
    G79("G79", "Cubic centimetre per hour bar"),
    G80("G80", "Cubic centimetre per minute bar"),
    G81("G81", "Cubic centimetre per second bar"),
    G82("G82", "Litre per day bar"),
    G83("G83", "Litre per hour bar"),
    G84("G84", "Litre per minute bar"),
    G85("G85", "Litre per second bar"),
    G86("G86", "Cubic metre per day bar"),
    G87("G87", "Cubic metre per hour bar"),
    G88("G88", "Cubic metre per minute bar"),
    G89("G89", "Cubic metre per second bar"),
    G90("G90", "Millilitre per day bar"),
    G91("G91", "Millilitre per hour bar"),
    G92("G92", "Millilitre per minute bar"),
    G93("G93", "Millilitre per second bar"),
    G94("G94", "Cubic centimetre per bar"),
    G95("G95", "Litre per bar"),
    G96("G96", "Cubic metre per bar"),
    G97("G97", "Millilitre per bar"),
    G98("G98", "Microhenry per kiloohm"),
    G99("G99", "Microhenry per ohm"),
    GB("GB", "Gallon (US) per day"),
    GBQ("GBQ", "Gigabecquerel"),
    GDW("GDW", "Gram, dry weight"),
    GE("GE", "Pound per gallon (US)"),
    GF("GF", "Gram per metre (gram per 100 centimetres)"),
    GFI("GFI", "Gram of fissile isotope"),
    GGR("GGR", "Great gross"),
    GIA("GIA", "Gill (US)"),
    GIC("GIC", "Gram, including container"),
    GII("GII", "Gill (UK)"),
    GIP("GIP", "Gram, including inner packaging"),
    GJ("GJ", "Gram per millilitre"),
    GL("GL", "Gram per litre"),
    GLD("GLD", "Dry gallon (US)"),
    GLI("GLI", "Gallon (UK)"),
    GLL("GLL", "Gallon (US)"),
    GM("GM", "Gram per square metre"),
    GO("GO", "Milligram per square metre"),
    GP("GP", "Milligram per cubic metre"),
    GQ("GQ", "Microgram per cubic metre"),
    GRM("GRM", "Gram"),
    GRN("GRN", "Grain"),
    GRO("GRO", "Gross"),
    GV("GV", "Gigajoule"),
    GWH("GWH", "Gigawatt hour"),
    H03("H03", "Henry per kiloohm"),
    H04("H04", "Henry per ohm"),
    H05("H05", "Millihenry per kiloohm"),
    H06("H06", "Millihenry per ohm"),
    H07("H07", "Pascal second per bar"),
    H08("H08", "Microbecquerel"),
    H09("H09", "Reciprocal year"),
    H10("H10", "Reciprocal hour"),
    H11("H11", "Reciprocal month"),
    H12("H12", "Degree Celsius per hour"),
    H13("H13", "Degree Celsius per minute"),
    H14("H14", "Degree Celsius per second"),
    H15("H15", "Square centimetre per gram"),
    H16("H16", "Square decametre"),
    H18("H18", "Square hectometre"),
    H19("H19", "Cubic hectometre"),
    H20("H20", "Cubic kilometre"),
    H21("H21", "Blank"),
    H22("H22", "Volt square inch per pound-force"),
    H23("H23", "Volt per inch"),
    H24("H24", "Volt per microsecond"),
    H25("H25", "Percent per kelvin"),
    H26("H26", "Ohm per metre"),
    H27("H27", "Degree per metre"),
    H28("H28", "Microfarad per kilometre"),
    H29("H29", "Microgram per litre"),
    H30("H30", "Square micrometre (square micron)"),
    H31("H31", "Ampere per kilogram"),
    H32("H32", "Ampere squared second"),
    H33("H33", "Farad per kilometre"),
    H34("H34", "Hertz metre"),
    H35("H35", "Kelvin metre per watt"),
    H36("H36", "Megaohm per kilometre"),
    H37("H37", "Megaohm per metre"),
    H38("H38", "Megaampere"),
    H39("H39", "Megahertz kilometre"),
    H40("H40", "Newton per ampere"),
    H41("H41", "Newton metre watt to the power minus 0,5"),
    H42("H42", "Pascal per metre"),
    H43("H43", "Siemens per centimetre"),
    H44("H44", "Teraohm"),
    H45("H45", "Volt second per metre"),
    H46("H46", "Volt per second"),
    H47("H47", "Watt per cubic metre"),
    H48("H48", "Attofarad"),
    H49("H49", "Centimetre per hour"),
    H50("H50", "Reciprocal cubic centimetre"),
    H51("H51", "Decibel per kilometre"),
    H52("H52", "Decibel per metre"),
    H53("H53", "Kilogram per bar"),
    H54("H54", "Kilogram per cubic decimetre kelvin"),
    H55("H55", "Kilogram per cubic decimetre bar"),
    H56("H56", "Kilogram per square metre second"),
    H57("H57", "Inch per two pi radiant"),
    H58("H58", "Metre per volt second"),
    H59("H59", "Square metre per newton"),
    H60("H60", "Cubic metre per cubic metre"),
    H61("H61", "Millisiemens per centimetre"),
    H62("H62", "Millivolt per minute"),
    H63("H63", "Milligram per square centimetre"),
    H64("H64", "Milligram per gram"),
    H65("H65", "Millilitre per cubic metre"),
    H66("H66", "Millimetre per year"),
    H67("H67", "Millimetre per hour"),
    H68("H68", "Millimole per gram"),
    H69("H69", "Picopascal per kilometre"),
    H70("H70", "Picosecond"),
    H71("H71", "Percent per month"),
    H72("H72", "Percent per hectobar"),
    H73("H73", "Percent per decakelvin"),
    H74("H74", "Watt per metre"),
    H75("H75", "Decapascal"),
    H76("H76", "Gram per millimetre"),
    H77("H77", "Module width"),
    H79("H79", "French gauge"),
    H80("H80", "Rack unit"),
    H81("H81", "Millimetre per minute"),
    H82("H82", "Big point"),
    H83("H83", "Litre per kilogram"),
    H84("H84", "Gram millimetre"),
    H85("H85", "Reciprocal week"),
    H87("H87", "Piece"),
    H88("H88", "Megaohm kilometre"),
    H89("H89", "Percent per ohm"),
    H90("H90", "Percent per degree"),
    H91("H91", "Percent per ten thousand"),
    H92("H92", "Percent per one hundred thousand"),
    H93("H93", "Percent per hundred"),
    H94("H94", "Percent per thousand"),
    H95("H95", "Percent per volt"),
    H96("H96", "Percent per bar"),
    H98("H98", "Percent per inch"),
    H99("H99", "Percent per metre"),
    HA("HA", "Hank"),
    HBA("HBA", "Hectobar"),
    HBX("HBX", "Hundred boxes"),
    HC("HC", "Hundred count"),
    HDW("HDW", "Hundred kilogram, dry weight"),
    HEA("HEA", "Head"),
    HGM("HGM", "Hectogram"),
    HH("HH", "Hundred cubic foot"),
    HIU("HIU", "Hundred international unit"),
    HKM("HKM", "Hundred kilogram, net mass"),
    HLT("HLT", "Hectolitre"),
    HM("HM", "Mile per hour (statute mile)"),
    HMQ("HMQ", "Million cubic metre"),
    HMT("HMT", "Hectometre"),
    HPA("HPA", "Hectolitre of pure alcohol"),
    HTZ("HTZ", "Hertz"),
    HUR("HUR", "Hour"),
    IA("IA", "Inch pound (pound inch)"),
    IE("IE", "Person"),
    INH("INH", "Inch"),
    INK("INK", "Square inch"),
    INQ("INQ", "Cubic inch"),
    ISD("ISD", "International sugar degree"),
    IU("IU", "Inch per second"),
    IUG("IUG", "International unit per gram"),
    IV("IV", "Inch per second squared"),
    J10("J10", "Percent per millimetre"),
    J12("J12", "Per mille per psi"),
    J13("J13", "Degree API"),
    J14("J14", "Degree Baume (origin scale)"),
    J15("J15", "Degree Baume (US heavy)"),
    J16("J16", "Degree Baume (US light)"),
    J17("J17", "Degree Balling"),
    J18("J18", "Degree Brix"),
    J19("J19", "Degree Fahrenheit hour square foot per British thermal unit (thermochemical)"),
    J2("J2", "Joule per kilogram"),
    J20("J20", "Degree Fahrenheit per kelvin"),
    J21("J21", "Degree Fahrenheit per bar"),
    J22("J22", "Degree Fahrenheit hour square foot per British thermal unit (international table)"),
    J23("J23", "Degree Fahrenheit per hour"),
    J24("J24", "Degree Fahrenheit per minute"),
    J25("J25", "Degree Fahrenheit per second"),
    J26("J26", "Reciprocal degree Fahrenheit"),
    J27("J27", "Degree Oechsle"),
    J28("J28", "Degree Rankine per hour"),
    J29("J29", "Degree Rankine per minute"),
    J30("J30", "Degree Rankine per second"),
    J31("J31", "Degree Twaddell"),
    J32("J32", "Micropoise"),
    J33("J33", "Microgram per kilogram"),
    J34("J34", "Microgram per cubic metre kelvin"),
    J35("J35", "Microgram per cubic metre bar"),
    J36("J36", "Microlitre per litre"),
    J38("J38", "Baud"),
    J39("J39", "British thermal unit (mean)"),
    J40("J40", "British thermal unit (international table) foot per hour square foot degree Fahrenheit"),
    J41("J41", "British thermal unit (international table) inch per hour square foot degree Fahrenheit"),
    J42("J42", "British thermal unit (international table) inch per second square foot degree Fahrenheit"),
    J43("J43", "British thermal unit (international table) per pound degree Fahrenheit"),
    J44("J44", "British thermal unit (international table) per minute"),
    J45("J45", "British thermal unit (international table) per second"),
    J46("J46", "British thermal unit (thermochemical) foot per hour square foot degree Fahrenheit"),
    J47("J47", "British thermal unit (thermochemical) per hour"),
    J48("J48", "British thermal unit (thermochemical) inch per hour square foot degree Fahrenheit"),
    J49("J49", "British thermal unit (thermochemical) inch per second square foot degree Fahrenheit"),
    J50("J50", "British thermal unit (thermochemical) per pound degree Fahrenheit"),
    J51("J51", "British thermal unit (thermochemical) per minute"),
    J52("J52", "British thermal unit (thermochemical) per second"),
    J53("J53", "Coulomb square metre per kilogram"),
    J54("J54", "Megabaud"),
    J55("J55", "Watt second"),
    J56("J56", "Bar per bar"),
    J57("J57", "Barrel (UK petroleum)"),
    J58("J58", "Barrel (UK petroleum) per minute"),
    J59("J59", "Barrel (UK petroleum) per day"),
    J60("J60", "Barrel (UK petroleum) per hour"),
    J61("J61", "Barrel (UK petroleum) per second"),
    J62("J62", "Barrel (US petroleum) per hour"),
    J63("J63", "Barrel (US petroleum) per second"),
    J64("J64", "Bushel (UK) per day"),
    J65("J65", "Bushel (UK) per hour"),
    J66("J66", "Bushel (UK) per minute"),
    J67("J67", "Bushel (UK) per second"),
    J68("J68", "Bushel (US dry) per day"),
    J69("J69", "Bushel (US dry) per hour"),
    J70("J70", "Bushel (US dry) per minute"),
    J71("J71", "Bushel (US dry) per second"),
    J72("J72", "Centinewton metre"),
    J73("J73", "Centipoise per kelvin"),
    J74("J74", "Centipoise per bar"),
    J75("J75", "Calorie (mean)"),
    J76("J76", "Calorie (international table) per gram degree Celsius"),
    J78("J78", "Calorie (thermochemical) per centimetre second degree Celsius"),
    J79("J79", "Calorie (thermochemical) per gram degree Celsius"),
    J81("J81", "Calorie (thermochemical) per minute"),
    J82("J82", "Calorie (thermochemical) per second"),
    J83("J83", "Clo"),
    J84("J84", "Centimetre per second kelvin"),
    J85("J85", "Centimetre per second bar"),
    J87("J87", "Cubic centimetre per cubic metre"),
    J90("J90", "Cubic decimetre per day"),
    J91("J91", "Cubic decimetre per cubic metre"),
    J92("J92", "Cubic decimetre per minute"),
    J93("J93", "Cubic decimetre per second"),
    J95("J95", "Ounce (UK fluid) per day"),
    J96("J96", "Ounce (UK fluid) per hour"),
    J97("J97", "Ounce (UK fluid) per minute"),
    J98("J98", "Ounce (UK fluid) per second"),
    J99("J99", "Ounce (US fluid) per day"),
    JE("JE", "Joule per kelvin"),
    JK("JK", "Megajoule per kilogram"),
    JM("JM", "Megajoule per cubic metre"),
    JNT("JNT", "Pipeline joint"),
    JOU("JOU", "Joule"),
    JPS("JPS", "Hundred metre"),
    JWL("JWL", "Number of jewels"),
    K1("K1", "Kilowatt demand"),
    K10("K10", "Ounce (US fluid) per hour"),
    K11("K11", "Ounce (US fluid) per minute"),
    K12("K12", "Ounce (US fluid) per second"),
    K13("K13", "Foot per degree Fahrenheit"),
    K14("K14", "Foot per hour"),
    K15("K15", "Foot pound-force per hour"),
    K16("K16", "Foot pound-force per minute"),
    K17("K17", "Foot per psi"),
    K18("K18", "Foot per second degree Fahrenheit"),
    K19("K19", "Foot per second psi"),
    K2("K2", "Kilovolt ampere reactive demand"),
    K20("K20", "Reciprocal cubic foot"),
    K21("K21", "Cubic foot per degree Fahrenheit"),
    K22("K22", "Cubic foot per day"),
    K23("K23", "Cubic foot per psi"),
    K26("K26", "Gallon (UK) per day"),
    K27("K27", "Gallon (UK) per hour"),
    K28("K28", "Gallon (UK) per second"),
    K3("K3", "Kilovolt ampere reactive hours"),
    K30("K30", "Gallon (US liquid) per second"),
    K31("K31", "Gram-force per square centimetre"),
    K32("K32", "Gill (UK) per day"),
    K33("K33", "Gill (UK) per hour"),
    K34("K34", "Gill (UK) per minute"),
    K35("K35", "Gill (UK) per second"),
    K36("K36", "Gill (US) per day"),
    K37("K37", "Gill (US) per hour"),
    K38("K38", "Gill (US) per minute"),
    K39("K39", "Gill (US) per second"),
    K40("K40", "Standard acceleration of free fall"),
    K41("K41", "Grain per gallon (US)"),
    K42("K42", "Horsepower (boiler)"),
    K43("K43", "Horsepower (electric)"),
    K45("K45", "Inch per degree Fahrenheit"),
    K46("K46", "Inch per psi"),
    K47("K47", "Inch per second degree Fahrenheit"),
    K48("K48", "Inch per second psi"),
    K49("K49", "Reciprocal cubic inch"),
    K50("K50", "Kilobaud"),
    K51("K51", "Kilocalorie (mean)"),
    K52("K52", "Kilocalorie (international table) per hour metre degree Celsius"),
    K53("K53", "Kilocalorie (thermochemical)"),
    K54("K54", "Kilocalorie (thermochemical) per minute"),
    K55("K55", "Kilocalorie (thermochemical) per second"),
    K58("K58", "Kilomole per hour"),
    K59("K59", "Kilomole per cubic metre kelvin"),
    K6("K6", "Kilolitre"),
    K60("K60", "Kilomole per cubic metre bar"),
    K61("K61", "Kilomole per minute"),
    K62("K62", "Litre per litre"),
    K63("K63", "Reciprocal litre"),
    K64("K64", "Pound (avoirdupois) per degree Fahrenheit"),
    K65("K65", "Pound (avoirdupois) square foot"),
    K66("K66", "Pound (avoirdupois) per day"),
    K67("K67", "Pound per foot hour"),
    K68("K68", "Pound per foot second"),
    K69("K69", "Pound (avoirdupois) per cubic foot degree Fahrenheit"),
    K70("K70", "Pound (avoirdupois) per cubic foot psi"),
    K71("K71", "Pound (avoirdupois) per gallon (UK)"),
    K73("K73", "Pound (avoirdupois) per hour degree Fahrenheit"),
    K74("K74", "Pound (avoirdupois) per hour psi"),
    K75("K75", "Pound (avoirdupois) per cubic inch degree Fahrenheit"),
    K76("K76", "Pound (avoirdupois) per cubic inch psi"),
    K77("K77", "Pound (avoirdupois) per psi"),
    K78("K78", "Pound (avoirdupois) per minute"),
    K79("K79", "Pound (avoirdupois) per minute degree Fahrenheit"),
    K80("K80", "Pound (avoirdupois) per minute psi"),
    K81("K81", "Pound (avoirdupois) per second"),
    K82("K82", "Pound (avoirdupois) per second degree Fahrenheit"),
    K83("K83", "Pound (avoirdupois) per second psi"),
    K84("K84", "Pound per cubic yard"),
    K85("K85", "Pound-force per square foot"),
    K86("K86", "Pound-force per square inch degree Fahrenheit"),
    K87("K87", "Psi cubic inch per second"),
    K88("K88", "Psi litre per second"),
    K89("K89", "Psi cubic metre per second"),
    K90("K90", "Psi cubic yard per second"),
    K91("K91", "Pound-force second per square foot"),
    K92("K92", "Pound-force second per square inch"),
    K93("K93", "Reciprocal psi"),
    K94("K94", "Quart (UK liquid) per day"),
    K95("K95", "Quart (UK liquid) per hour"),
    K96("K96", "Quart (UK liquid) per minute"),
    K97("K97", "Quart (UK liquid) per second"),
    K98("K98", "Quart (US liquid) per day"),
    K99("K99", "Quart (US liquid) per hour"),
    KA("KA", "Cake"),
    KAT("KAT", "Katal"),
    KB("KB", "Kilocharacter"),
    KBA("KBA", "Kilobar"),
    KCC("KCC", "Kilogram of choline chloride"),
    KDW("KDW", "Kilogram drained net weight"),
    KEL("KEL", "Kelvin"),
    KGM("KGM", "Kilogram"),
    KGS("KGS", "Kilogram per second"),
    KHY("KHY", "Kilogram of hydrogen peroxide"),
    KHZ("KHZ", "Kilohertz"),
    KI("KI", "Kilogram per millimetre width"),
    KIC("KIC", "Kilogram, including container"),
    KIP("KIP", "Kilogram, including inner packaging"),
    KJ("KJ", "Kilosegment"),
    KJO("KJO", "Kilojoule"),
    KL("KL", "Kilogram per metre"),
    KLK("KLK", "Lactic dry material percentage"),
    KLX("KLX", "Kilolux"),
    KMA("KMA", "Kilogram of methylamine"),
    KMH("KMH", "Kilometre per hour"),
    KMK("KMK", "Square kilometre"),
    KMQ("KMQ", "Kilogram per cubic metre"),
    KMT("KMT", "Kilometre"),
    KNI("KNI", "Kilogram of nitrogen"),
    KNM("KNM", "Kilonewton per square metre"),
    KNS("KNS", "Kilogram named substance"),
    KNT("KNT", "Knot"),
    KO("KO", "Milliequivalence caustic potash per gram of product"),
    KPA("KPA", "Kilopascal"),
    KPH("KPH", "Kilogram of potassium hydroxide (caustic potash)"),
    KPO("KPO", "Kilogram of potassium oxide"),
    KPP("KPP", "Kilogram of phosphorus pentoxide (phosphoric anhydride)"),
    KR("KR", "Kiloroentgen"),
    KSD("KSD", "Kilogram of substance 90 % dry"),
    KSH("KSH", "Kilogram of sodium hydroxide (caustic soda)"),
    KT("KT", "Kit"),
    KTN("KTN", "Kilotonne"),
    KUR("KUR", "Kilogram of uranium"),
    KVA("KVA", "Kilovolt - ampere"),
    KVR("KVR", "Kilovar"),
    KVT("KVT", "Kilovolt"),
    KW("KW", "Kilogram per millimetre"),
    KWH("KWH", "Kilowatt hour"),
    KWN("KWN", "Kilowatt hour per normalized cubic metre"),
    KWO("KWO", "Kilogram of tungsten trioxide"),
    KWS("KWS", "Kilowatt hour per standard cubic metre"),
    KWT("KWT", "Kilowatt"),
    KX("KX", "Millilitre per kilogram"),
    L10("L10", "Quart (US liquid) per minute"),
    L11("L11", "Quart (US liquid) per second"),
    L12("L12", "Metre per second kelvin"),
    L13("L13", "Metre per second bar"),
    L14("L14", "Square metre hour degree Celsius per kilocalorie (international table)"),
    L15("L15", "Millipascal second per kelvin"),
    L16("L16", "Millipascal second per bar"),
    L17("L17", "Milligram per cubic metre kelvin"),
    L18("L18", "Milligram per cubic metre bar"),
    L19("L19", "Millilitre per litre"),
    L2("L2", "Litre per minute"),
    L20("L20", "Reciprocal cubic millimetre"),
    L21("L21", "Cubic millimetre per cubic metre"),
    L23("L23", "Mole per hour"),
    L24("L24", "Mole per kilogram kelvin"),
    L25("L25", "Mole per kilogram bar"),
    L26("L26", "Mole per litre kelvin"),
    L27("L27", "Mole per litre bar"),
    L28("L28", "Mole per cubic metre kelvin"),
    L29("L29", "Mole per cubic metre bar"),
    L30("L30", "Mole per minute"),
    L31("L31", "Milliroentgen aequivalent men"),
    L32("L32", "Nanogram per kilogram"),
    L33("L33", "Ounce (avoirdupois) per day"),
    L34("L34", "Ounce (avoirdupois) per hour"),
    L35("L35", "Ounce (avoirdupois) per minute"),
    L36("L36", "Ounce (avoirdupois) per second"),
    L37("L37", "Ounce (avoirdupois) per gallon (UK)"),
    L38("L38", "Ounce (avoirdupois) per gallon (US)"),
    L39("L39", "Ounce (avoirdupois) per cubic inch"),
    L40("L40", "Ounce (avoirdupois)-force"),
    L41("L41", "Ounce (avoirdupois)-force inch"),
    L42("L42", "Picosiemens per metre"),
    L43("L43", "Peck (UK)"),
    L44("L44", "Peck (UK) per day"),
    L45("L45", "Peck (UK) per hour"),
    L46("L46", "Peck (UK) per minute"),
    L47("L47", "Peck (UK) per second"),
    L48("L48", "Peck (US dry) per day"),
    L49("L49", "Peck (US dry) per hour"),
    L50("L50", "Peck (US dry) per minute"),
    L51("L51", "Peck (US dry) per second"),
    L52("L52", "Psi per psi"),
    L53("L53", "Pint (UK) per day"),
    L54("L54", "Pint (UK) per hour"),
    L55("L55", "Pint (UK) per minute"),
    L56("L56", "Pint (UK) per second"),
    L57("L57", "Pint (US liquid) per day"),
    L58("L58", "Pint (US liquid) per hour"),
    L59("L59", "Pint (US liquid) per minute"),
    L60("L60", "Pint (US liquid) per second"),
    L63("L63", "Slug per day"),
    L64("L64", "Slug per foot second"),
    L65("L65", "Slug per cubic foot"),
    L66("L66", "Slug per hour"),
    L67("L67", "Slug per minute"),
    L68("L68", "Slug per second"),
    L69("L69", "Tonne per kelvin"),
    L70("L70", "Tonne per bar"),
    L71("L71", "Tonne per day"),
    L72("L72", "Tonne per day kelvin"),
    L73("L73", "Tonne per day bar"),
    L74("L74", "Tonne per hour kelvin"),
    L75("L75", "Tonne per hour bar"),
    L76("L76", "Tonne per cubic metre kelvin"),
    L77("L77", "Tonne per cubic metre bar"),
    L78("L78", "Tonne per minute"),
    L79("L79", "Tonne per minute kelvin"),
    L80("L80", "Tonne per minute bar"),
    L81("L81", "Tonne per second"),
    L82("L82", "Tonne per second kelvin"),
    L83("L83", "Tonne per second bar"),
    L84("L84", "Ton (UK shipping)"),
    L85("L85", "Ton long per day"),
    L86("L86", "Ton (US shipping)"),
    L87("L87", "Ton short per degree Fahrenheit"),
    L88("L88", "Ton short per day"),
    L89("L89", "Ton short per hour degree Fahrenheit"),
    L90("L90", "Ton short per hour psi"),
    L91("L91", "Ton short per psi"),
    L92("L92", "Ton (UK long) per cubic yard"),
    L93("L93", "Ton (US short) per cubic yard"),
    L94("L94", "Ton-force (US short)"),
    L95("L95", "Common year"),
    L96("L96", "Sidereal year"),
    L98("L98", "Yard per degree Fahrenheit"),
    L99("L99", "Yard per psi"),
    LA("LA", "Pound per cubic inch"),
    LAC("LAC", "Lactose excess percentage"),
    LBR("LBR", "Pound"),
    LBT("LBT", "Troy pound (US)"),
    LD("LD", "Litre per day"),
    LEF("LEF", "Leaf"),
    LF("LF", "Linear foot"),
    LH("LH", "Labour hour"),
    LK("LK", "Link"),
    LM("LM", "Linear metre"),
    LN("LN", "Length"),
    LO("LO", "Lot  [unit of procurement]"),
    LP("LP", "Liquid pound"),
    LPA("LPA", "Litre of pure alcohol"),
    LR("LR", "Layer"),
    LS("LS", "Lump sum"),
    LTN("LTN", "Ton (UK) or long ton (US)"),
    LTR("LTR", "Litre"),
    LUB("LUB", "Metric ton, lubricating oil"),
    LUM("LUM", "Lumen"),
    LUX("LUX", "Lux"),
    LY("LY", "Linear yard"),
    M1("M1", "Milligram per litre"),
    M10("M10", "Reciprocal cubic yard"),
    M11("M11", "Cubic yard per degree Fahrenheit"),
    M12("M12", "Cubic yard per day"),
    M13("M13", "Cubic yard per hour"),
    M14("M14", "Cubic yard per psi"),
    M15("M15", "Cubic yard per minute"),
    M16("M16", "Cubic yard per second"),
    M17("M17", "Kilohertz metre"),
    M18("M18", "Gigahertz metre"),
    M19("M19", "Beaufort"),
    M20("M20", "Reciprocal megakelvin or megakelvin to the power minus one"),
    M21("M21", "Reciprocal kilovolt - ampere reciprocal hour"),
    M22("M22", "Millilitre per square centimetre minute"),
    M23("M23", "Newton per centimetre"),
    M24("M24", "Ohm kilometre"),
    M25("M25", "Percent per degree Celsius"),
    M26("M26", "Gigaohm per metre"),
    M27("M27", "Megahertz metre"),
    M29("M29", "Kilogram per kilogram"),
    M30("M30", "Reciprocal volt - ampere reciprocal second"),
    M31("M31", "Kilogram per kilometre"),
    M32("M32", "Pascal second per litre"),
    M33("M33", "Millimole per litre"),
    M34("M34", "Newton metre per square metre"),
    M35("M35", "Millivolt - ampere"),
    M36("M36", "30-day month"),
    M37("M37", "Actual/360"),
    M38("M38", "Kilometre per second squared"),
    M39("M39", "Centimetre per second squared"),
    M4("M4", "Monetary value"),
    M40("M40", "Yard per second squared"),
    M41("M41", "Millimetre per second squared"),
    M42("M42", "Mile (statute mile) per second squared"),
    M43("M43", "Mil"),
    M44("M44", "Revolution"),
    M45("M45", "Degree [unit of angle] per second squared"),
    M46("M46", "Revolution per minute"),
    M47("M47", "Circular mil"),
    M48("M48", "Square mile (based on U.S. survey foot)"),
    M49("M49", "Chain (based on U.S. survey foot)"),
    M5("M5", "Microcurie"),
    M50("M50", "Furlong"),
    M51("M51", "Foot (U.S. survey)"),
    M52("M52", "Mile (based on U.S. survey foot)"),
    M53("M53", "Metre per pascal"),
    M55("M55", "Metre per radiant"),
    M56("M56", "Shake"),
    M57("M57", "Mile per minute"),
    M58("M58", "Mile per second"),
    M59("M59", "Metre per second pascal"),
    M60("M60", "Metre per hour"),
    M61("M61", "Inch per year"),
    M62("M62", "Kilometre per second"),
    M63("M63", "Inch per minute"),
    M64("M64", "Yard per second"),
    M65("M65", "Yard per minute"),
    M66("M66", "Yard per hour"),
    M67("M67", "Acre-foot (based on U.S. survey foot)"),
    M68("M68", "Cord (128 ft3)"),
    M69("M69", "Cubic mile (UK statute)"),
    M7("M7", "Micro-inch"),
    M70("M70", "Ton, register"),
    M71("M71", "Cubic metre per pascal"),
    M72("M72", "Bel"),
    M73("M73", "Kilogram per cubic metre pascal"),
    M74("M74", "Kilogram per pascal"),
    M75("M75", "Kilopound-force"),
    M76("M76", "Poundal"),
    M77("M77", "Kilogram metre per second squared"),
    M78("M78", "Pond"),
    M79("M79", "Square foot per hour"),
    M80("M80", "Stokes per pascal"),
    M81("M81", "Square centimetre per second"),
    M82("M82", "Square metre per second pascal"),
    M83("M83", "Denier"),
    M84("M84", "Pound per yard"),
    M85("M85", "Ton, assay"),
    M86("M86", "Pfund"),
    M87("M87", "Kilogram per second pascal"),
    M88("M88", "Tonne per month"),
    M89("M89", "Tonne per year"),
    M9("M9", "Million Btu per 1000 cubic foot"),
    M90("M90", "Kilopound per hour"),
    M91("M91", "Pound per pound"),
    M92("M92", "Pound-force foot"),
    M93("M93", "Newton metre per radian"),
    M94("M94", "Kilogram metre"),
    M95("M95", "Poundal foot"),
    M96("M96", "Poundal inch"),
    M97("M97", "Dyne metre"),
    M98("M98", "Kilogram centimetre per second"),
    M99("M99", "Gram centimetre per second"),
    MAH("MAH", "Megavolt ampere reactive hour"),
    MAL("MAL", "Megalitre"),
    MAM("MAM", "Megametre"),
    MAR("MAR", "Megavar"),
    MAW("MAW", "Megawatt"),
    MBE("MBE", "Thousand standard brick equivalent"),
    MBF("MBF", "Thousand board foot"),
    MBR("MBR", "Millibar"),
    MC("MC", "Microgram"),
    MCU("MCU", "Millicurie"),
    MD("MD", "Air dry metric ton"),
    MGM("MGM", "Milligram"),
    MHZ("MHZ", "Megahertz"),
    MIK("MIK", "Square mile (statute mile)"),
    MIL("MIL", "Thousand"),
    MIN("MIN", "Minute [unit of time]"),
    MIO("MIO", "Million"),
    MIU("MIU", "Million international unit"),
    MLD("MLD", "Milliard"),
    MLT("MLT", "Millilitre"),
    MMK("MMK", "Square millimetre"),
    MMQ("MMQ", "Cubic millimetre"),
    MMT("MMT", "Millimetre"),
    MND("MND", "Kilogram, dry weight"),
    MON("MON", "Month"),
    MPA("MPA", "Megapascal"),
    MQH("MQH", "Cubic metre per hour"),
    MQS("MQS", "Cubic metre per second"),
    MSK("MSK", "Metre per second squared"),
    MTK("MTK", "Square metre"),
    MTQ("MTQ", "Cubic metre"),
    MTR("MTR", "Metre"),
    MTS("MTS", "Metre per second"),
    MVA("MVA", "Megavolt - ampere"),
    MWH("MWH", "Megawatt hour (1000 kW.h)"),
    N1("N1", "Pen calorie"),
    N10("N10", "Pound foot per second"),
    N11("N11", "Pound inch per second"),
    N12("N12", "Pferdestaerke"),
    N13("N13", "Centimetre of mercury (0 ºC)"),
    N14("N14", "Centimetre of water (4 ºC)"),
    N15("N15", "Foot of water (39.2 ºF)"),
    N16("N16", "Inch of mercury (32 ºF)"),
    N17("N17", "Inch of mercury (60 ºF)"),
    N18("N18", "Inch of water (39.2 ºF)"),
    N19("N19", "Inch of water (60 ºF)"),
    N20("N20", "Kip per square inch"),
    N21("N21", "Poundal per square foot"),
    N22("N22", "Ounce (avoirdupois) per square inch"),
    N23("N23", "Conventional metre of water"),
    N24("N24", "Gram per square millimetre"),
    N25("N25", "Pound per square yard"),
    N26("N26", "Poundal per square inch"),
    N27("N27", "Foot to the fourth power"),
    N28("N28", "Cubic decimetre per kilogram"),
    N29("N29", "Cubic foot per pound"),
    N3("N3", "Print point"),
    N30("N30", "Cubic inch per pound"),
    N31("N31", "Kilonewton per metre"),
    N32("N32", "Poundal per inch"),
    N33("N33", "Pound-force per yard"),
    N34("N34", "Poundal second per square foot"),
    N35("N35", "Poise per pascal"),
    N36("N36", "Newton second per square metre"),
    N37("N37", "Kilogram per metre second"),
    N38("N38", "Kilogram per metre minute"),
    N39("N39", "Kilogram per metre day"),
    N40("N40", "Kilogram per metre hour"),
    N41("N41", "Gram per centimetre second"),
    N42("N42", "Poundal second per square inch"),
    N43("N43", "Pound per foot minute"),
    N44("N44", "Pound per foot day"),
    N45("N45", "Cubic metre per second pascal"),
    N46("N46", "Foot poundal"),
    N47("N47", "Inch poundal"),
    N48("N48", "Watt per square centimetre"),
    N49("N49", "Watt per square inch"),
    N50("N50", "British thermal unit (international table) per square foot hour"),
    N51("N51", "British thermal unit (thermochemical) per square foot hour"),
    N52("N52", "British thermal unit (thermochemical) per square foot minute"),
    N53("N53", "British thermal unit (international table) per square foot second"),
    N54("N54", "British thermal unit (thermochemical) per square foot second"),
    N55("N55", "British thermal unit (international table) per square inch second"),
    N56("N56", "Calorie (thermochemical) per square centimetre minute"),
    N57("N57", "Calorie (thermochemical) per square centimetre second"),
    N58("N58", "British thermal unit (international table) per cubic foot"),
    N59("N59", "British thermal unit (thermochemical) per cubic foot"),
    N60("N60", "British thermal unit (international table) per degree Fahrenheit"),
    N61("N61", "British thermal unit (thermochemical) per degree Fahrenheit"),
    N62("N62", "British thermal unit (international table) per degree Rankine"),
    N63("N63", "British thermal unit (thermochemical) per degree Rankine"),
    N64("N64", "British thermal unit (thermochemical) per pound degree Rankine"),
    N65("N65", "Kilocalorie (international table) per gram kelvin"),
    N66("N66", "British thermal unit (39 ºF)"),
    N67("N67", "British thermal unit (59 ºF)"),
    N68("N68", "British thermal unit (60 ºF)"),
    N69("N69", "Calorie (20 ºC)"),
    N70("N70", "Quad (1015 BtuIT)"),
    N71("N71", "Therm (EC)"),
    N72("N72", "Therm (U.S.)"),
    N73("N73", "British thermal unit (thermochemical) per pound"),
    N74("N74", "British thermal unit (international table) per hour square foot degree Fahrenheit"),
    N75("N75", "British thermal unit (thermochemical) per hour square foot degree Fahrenheit"),
    N76("N76", "British thermal unit (international table) per second square foot degree Fahrenheit"),
    N77("N77", "British thermal unit (thermochemical) per second square foot degree Fahrenheit"),
    N78("N78", "Kilowatt per square metre kelvin"),
    N79("N79", "Kelvin per pascal"),
    N80("N80", "Watt per metre degree Celsius"),
    N81("N81", "Kilowatt per metre kelvin"),
    N82("N82", "Kilowatt per metre degree Celsius"),
    N83("N83", "Metre per degree Celcius metre"),
    N84("N84", "Degree Fahrenheit hour per British thermal unit (international table)"),
    N85("N85", "Degree Fahrenheit hour per British thermal unit (thermochemical)"),
    N86("N86", "Degree Fahrenheit second per British thermal unit (international table)"),
    N87("N87", "Degree Fahrenheit second per British thermal unit (thermochemical)"),
    N88("N88", "Degree Fahrenheit hour square foot per British thermal unit (international table) inch"),
    N89("N89", "Degree Fahrenheit hour square foot per British thermal unit (thermochemical) inch"),
    N90("N90", "Kilofarad"),
    N91("N91", "Reciprocal joule"),
    N92("N92", "Picosiemens"),
    N93("N93", "Ampere per pascal"),
    N94("N94", "Franklin"),
    N95("N95", "Ampere minute"),
    N96("N96", "Biot"),
    N97("N97", "Gilbert"),
    N98("N98", "Volt per pascal"),
    N99("N99", "Picovolt"),
    NA("NA", "Milligram per kilogram"),
    NAR("NAR", "Article"),
    NCL("NCL", "Number of cells"),
    NEW("NEW", "Newton"),
    NF("NF", "Message"),
    NIL("NIL", "Nil"),
    NIU("NIU", "Number of international units"),
    NL("NL", "Load"),
    NM3("NM3", "Normalised cubic metre"),
    NMI("NMI", "Nautical mile"),
    NMP("NMP", "Number of packs"),
    NPT("NPT", "Number of parts"),
    NT("NT", "Net ton"),
    NU("NU", "Newton metre"),
    NX("NX", "Part per thousand"),
    OA("OA", "Panel"),
    ODE("ODE", "Ozone depletion equivalent"),
    ODG("ODG", "ODS Grams"),
    ODK("ODK", "ODS Kilograms"),
    ODM("ODM", "ODS Milligrams"),
    OHM("OHM", "Ohm"),
    ON("ON", "Ounce per square yard"),
    ONZ("ONZ", "Ounce (avoirdupois)"),
    OPM("OPM", "Oscillations per minute"),
    OT("OT", "Overtime hour"),
    OZA("OZA", "Fluid ounce (US)"),
    OZI("OZI", "Fluid ounce (UK)"),
    P1("P1", "Percent"),
    P10("P10", "Coulomb per metre"),
    P11("P11", "Kiloweber"),
    P12("P12", "Gamma"),
    P13("P13", "Kilotesla"),
    P14("P14", "Joule per second"),
    P15("P15", "Joule per minute"),
    P16("P16", "Joule per hour"),
    P17("P17", "Joule per day"),
    P18("P18", "Kilojoule per second"),
    P19("P19", "Kilojoule per minute"),
    P2("P2", "Pound per foot"),
    P20("P20", "Kilojoule per hour"),
    P21("P21", "Kilojoule per day"),
    P22("P22", "Nanoohm"),
    P23("P23", "Ohm circular-mil per foot"),
    P24("P24", "Kilohenry"),
    P25("P25", "Lumen per square foot"),
    P26("P26", "Phot"),
    P27("P27", "Footcandle"),
    P28("P28", "Candela per square inch"),
    P29("P29", "Footlambert"),
    P30("P30", "Lambert"),
    P31("P31", "Stilb"),
    P32("P32", "Candela per square foot"),
    P33("P33", "Kilocandela"),
    P34("P34", "Millicandela"),
    P35("P35", "Hefner-Kerze"),
    P36("P36", "International candle"),
    P37("P37", "British thermal unit (international table) per square foot"),
    P38("P38", "British thermal unit (thermochemical) per square foot"),
    P39("P39", "Calorie (thermochemical) per square centimetre"),
    P40("P40", "Langley"),
    P41("P41", "Decade (logarithmic)"),
    P42("P42", "Pascal squared second"),
    P43("P43", "Bel per metre"),
    P44("P44", "Pound mole"),
    P45("P45", "Pound mole per second"),
    P46("P46", "Pound mole per minute"),
    P47("P47", "Kilomole per kilogram"),
    P48("P48", "Pound mole per pound"),
    P49("P49", "Newton square metre per ampere"),
    P5("P5", "Five pack"),
    P50("P50", "Weber metre"),
    P51("P51", "Mol per kilogram pascal"),
    P52("P52", "Mol per cubic metre pascal"),
    P53("P53", "Unit pole"),
    P54("P54", "Milligray per second"),
    P55("P55", "Microgray per second"),
    P56("P56", "Nanogray per second"),
    P57("P57", "Gray per minute"),
    P58("P58", "Milligray per minute"),
    P59("P59", "Microgray per minute"),
    P60("P60", "Nanogray per minute"),
    P61("P61", "Gray per hour"),
    P62("P62", "Milligray per hour"),
    P63("P63", "Microgray per hour"),
    P64("P64", "Nanogray per hour"),
    P65("P65", "Sievert per second"),
    P66("P66", "Millisievert per second"),
    P67("P67", "Microsievert per second"),
    P68("P68", "Nanosievert per second"),
    P69("P69", "Rem per second"),
    P70("P70", "Sievert per hour"),
    P71("P71", "Millisievert per hour"),
    P72("P72", "Microsievert per hour"),
    P73("P73", "Nanosievert per hour"),
    P74("P74", "Sievert per minute"),
    P75("P75", "Millisievert per minute"),
    P76("P76", "Microsievert per minute"),
    P77("P77", "Nanosievert per minute"),
    P78("P78", "Reciprocal square inch"),
    P79("P79", "Pascal square metre per kilogram"),
    P80("P80", "Millipascal per metre"),
    P81("P81", "Kilopascal per metre"),
    P82("P82", "Hectopascal per metre"),
    P83("P83", "Standard atmosphere per metre"),
    P84("P84", "Technical atmosphere per metre"),
    P85("P85", "Torr per metre"),
    P86("P86", "Psi per inch"),
    P87("P87", "Cubic metre per second square metre"),
    P88("P88", "Rhe"),
    P89("P89", "Pound-force foot per inch"),
    P90("P90", "Pound-force inch per inch"),
    P91("P91", "Perm (0 ºC)"),
    P92("P92", "Perm (23 ºC)"),
    P93("P93", "Byte per second"),
    P94("P94", "Kilobyte per second"),
    P95("P95", "Megabyte per second"),
    P96("P96", "Reciprocal volt"),
    P97("P97", "Reciprocal radian"),
    P98("P98", "Pascal to the power sum of stoichiometric numbers"),
    P99("P99", "Mole per cubiv metre to the power sum of stoichiometric numbers"),
    PAL("PAL", "Pascal"),
    PD("PD", "Pad"),
    PFL("PFL", "Proof litre"),
    PGL("PGL", "Proof gallon"),
    PI("PI", "Pitch"),
    PLA("PLA", "Degree Plato"),
    PO("PO", "Pound per inch of length"),
    PQ("PQ", "Page per inch"),
    PR("PR", "Pair"),
    PS("PS", "Pound-force per square inch"),
    PTD("PTD", "Dry pint (US)"),
    PTI("PTI", "Pint (UK)"),
    PTL("PTL", "Liquid pint (US)"),
    PTN("PTN", "Portion"),
    Q10("Q10", "Joule per tesla"),
    Q11("Q11", "Erlang"),
    Q12("Q12", "Octet"),
    Q13("Q13", "Octet per second"),
    Q14("Q14", "Shannon"),
    Q15("Q15", "Hartley"),
    Q16("Q16", "Natural unit of information"),
    Q17("Q17", "Shannon per second"),
    Q18("Q18", "Hartley per second"),
    Q19("Q19", "Natural unit of information per second"),
    Q20("Q20", "Second per kilogramm"),
    Q21("Q21", "Watt square metre"),
    Q22("Q22", "Second per radian cubic metre"),
    Q23("Q23", "Weber to the power minus one"),
    Q24("Q24", "Reciprocal inch"),
    Q25("Q25", "Dioptre"),
    Q26("Q26", "One per one"),
    Q27("Q27", "Newton metre per metre"),
    Q28("Q28", "Kilogram per square metre pascal second"),
    Q29("Q29", "Microgram per hectogram"),
    Q3("Q3", "Meal"),
    Q30("Q30", "PH (potential of Hydrogen)"),
    Q31("Q31", "Kilojoule per gram"),
    Q32("Q32", "Femtolitre"),
    Q33("Q33", "Picolitre"),
    Q34("Q34", "Nanolitre"),
    Q35("Q35", "Megawatts per minute"),
    Q36("Q36", "Square metre per cubic metre"),
    Q37("Q37", "Standard cubic metre per day"),
    Q38("Q38", "Standard cubic metre per hour"),
    Q39("Q39", "Normalized cubic metre per day"),
    Q40("Q40", "Normalized cubic metre per hour"),
    Q41("Q41", "Joule per normalised cubic metre"),
    Q42("Q42", "Joule per standard cubic metre"),
    QA("QA", "Page - facsimile"),
    QAN("QAN", "Quarter (of a year)"),
    QB("QB", "Page - hardcopy"),
    QR("QR", "Quire"),
    QTD("QTD", "Dry quart (US)"),
    QTI("QTI", "Quart (UK)"),
    QTL("QTL", "Liquid quart (US)"),
    QTR("QTR", "Quarter (UK)"),
    R1("R1", "Pica"),
    R9("R9", "Thousand cubic metre"),
    RH("RH", "Running or operating hour"),
    RM("RM", "Ream"),
    ROM("ROM", "Room"),
    RP("RP", "Pound per ream"),
    RPM("RPM", "Revolutions per minute"),
    RPS("RPS", "Revolutions per second"),
    RT("RT", "Revenue ton mile"),
    S3("S3", "Square foot per second"),
    S4("S4", "Square metre per second"),
    SAN("SAN", "Half year (6 months)"),
    SCO("SCO", "Score"),
    SCR("SCR", "Scruple"),
    SEC("SEC", "Second [unit of time]"),
    SET("SET", "Set"),
    SG("SG", "Segment"),
    SIE("SIE", "Siemens"),
    SM3("SM3", "Standard cubic metre"),
    SMI("SMI", "Mile (statute mile)"),
    SQ("SQ", "Square"),
    SQR("SQR", "Square, roofing"),
    SR("SR", "Strip"),
    STC("STC", "Stick"),
    STI("STI", "Stone (UK)"),
    STK("STK", "Stick, cigarette"),
    STL("STL", "Standard litre"),
    STN("STN", "Ton (US) or short ton (UK/US)"),
    STW("STW", "Straw"),
    SW("SW", "Skein"),
    SX("SX", "Shipment"),
    SYR("SYR", "Syringe"),
    T0("T0", "Telecommunication line in service"),
    T3("T3", "Thousand piece"),
    TAH("TAH", "Kiloampere hour (thousand ampere hour)"),
    TAN("TAN", "Total acid number"),
    TI("TI", "Thousand square inch"),
    TIC("TIC", "Metric ton, including container"),
    TIP("TIP", "Metric ton, including inner packaging"),
    TKM("TKM", "Tonne kilometre"),
    TMS("TMS", "Kilogram of imported meat, less offal"),
    TNE("TNE", "Tonne (metric ton)"),
    TP("TP", "Ten pack"),
    TPI("TPI", "Teeth per inch"),
    TPR("TPR", "Ten pair"),
    TQD("TQD", "Thousand cubic metre per day"),
    TRL("TRL", "Trillion (EUR)"),
    TST("TST", "Ten set"),
    TTS("TTS", "Ten thousand sticks"),
    U1("U1", "Treatment"),
    U2("U2", "Tablet"),
    UB("UB", "Telecommunication line in service average"),
    UC("UC", "Telecommunication port"),
    VA("VA", "Volt - ampere per kilogram"),
    VLT("VLT", "Volt"),
    VP("VP", "Percent volume"),
    W2("W2", "Wet kilo"),
    W4("W4", "Two week"),
    WA("WA", "Watt per kilogram"),
    WB("WB", "Wet pound"),
    WCD("WCD", "Cord"),
    WE("WE", "Wet ton"),
    WEB("WEB", "Weber"),
    WEE("WEE", "Week"),
    WG("WG", "Wine gallon"),
    WHR("WHR", "Watt hour"),
    WM("WM", "Working month"),
    WSD("WSD", "Standard"),
    WTT("WTT", "Watt"),
    X1("X1", "Gunter's chain"),
    X1A("X1A", "Drum, steel"),
    X1B("X1B", "Drum, aluminium"),
    X1D("X1D", "Drum, plywood"),
    X1F("X1F", "Container, flexible"),
    X1G("X1G", "Drum, fibre"),
    X1W("X1W", "Drum, wooden"),
    X2C("X2C", "Barrel, wooden"),
    X3A("X3A", "Jerrican, steel"),
    X3H("X3H", "Jerrican, plastic"),
    X43("X43", "Bag, super bulk"),
    X44("X44", "Bag, polybag"),
    X4A("X4A", "Box, steel"),
    X4B("X4B", "Box, aluminium"),
    X4C("X4C", "Box, natural wood"),
    X4D("X4D", "Box, plywood"),
    X4F("X4F", "Box, reconstituted wood"),
    X4G("X4G", "Box, fibreboard"),
    X4H("X4H", "Box, plastic"),
    X5H("X5H", "Bag, woven plastic"),
    X5L("X5L", "Bag, textile"),
    X5M("X5M", "Bag, paper"),
    X6H("X6H", "Composite packaging, plastic receptacle"),
    X6P("X6P", "Composite packaging, glass receptacle"),
    X7A("X7A", "Case, car"),
    X7B("X7B", "Case, wooden"),
    X8A("X8A", "Pallet, wooden"),
    X8B("X8B", "Crate, wooden"),
    X8C("X8C", "Bundle, wooden"),
    XAA("XAA", "Intermediate bulk container, rigid plastic"),
    XAB("XAB", "Receptacle, fibre"),
    XAC("XAC", "Receptacle, paper"),
    XAD("XAD", "Receptacle, wooden"),
    XAE("XAE", "Aerosol"),
    XAF("XAF", "Pallet, modular, collars 80cms * 60cms"),
    XAG("XAG", "Pallet, shrinkwrapped"),
    XAH("XAH", "Pallet, 100cms * 110cms"),
    XAI("XAI", "Clamshell"),
    XAJ("XAJ", "Cone"),
    XAL("XAL", "Ball"),
    XAM("XAM", "Ampoule, non-protected"),
    XAP("XAP", "Ampoule, protected"),
    XAT("XAT", "Atomizer"),
    XAV("XAV", "Capsule"),
    XB4("XB4", "Belt"),
    XBA("XBA", "Barrel"),
    XBB("XBB", "Bobbin"),
    XBC("XBC", "Bottlecrate / bottlerack"),
    XBD("XBD", "Board"),
    XBE("XBE", "Bundle"),
    XBF("XBF", "Balloon, non-protected"),
    XBG("XBG", "Bag"),
    XBH("XBH", "Bunch"),
    XBI("XBI", "Bin"),
    XBJ("XBJ", "Bucket"),
    XBK("XBK", "Basket"),
    XBL("XBL", "Bale, compressed"),
    XBM("XBM", "Basin"),
    XBN("XBN", "Bale, non-compressed"),
    XBO("XBO", "Bottle, non-protected, cylindrical"),
    XBP("XBP", "Balloon, protected"),
    XBQ("XBQ", "Bottle, protected cylindrical"),
    XBR("XBR", "Bar"),
    XBS("XBS", "Bottle, non-protected, bulbous"),
    XBT("XBT", "Bolt"),
    XBU("XBU", "Butt"),
    XBV("XBV", "Bottle, protected bulbous"),
    XBW("XBW", "Box, for liquids"),
    XBX("XBX", "Box"),
    XBY("XBY", "Board, in bundle/bunch/truss"),
    XBZ("XBZ", "Bars, in bundle/bunch/truss"),
    XCA("XCA", "Can, rectangular"),
    XCB("XCB", "Crate, beer"),
    XCC("XCC", "Churn"),
    XCD("XCD", "Can, with handle and spout"),
    XCE("XCE", "Creel"),
    XCF("XCF", "Coffer"),
    XCG("XCG", "Cage"),
    XCH("XCH", "Chest"),
    XCI("XCI", "Canister"),
    XCJ("XCJ", "Coffin"),
    XCK("XCK", "Cask"),
    XCL("XCL", "Coil"),
    XCM("XCM", "Card"),
    XCN("XCN", "Container, not otherwise specified as transport equipment"),
    XCO("XCO", "Carboy, non-protected"),
    XCP("XCP", "Carboy, protected"),
    XCQ("XCQ", "Cartridge"),
    XCR("XCR", "Crate"),
    XCS("XCS", "Case"),
    XCT("XCT", "Carton"),
    XCU("XCU", "Cup"),
    XCV("XCV", "Cover"),
    XCW("XCW", "Cage, roll"),
    XCX("XCX", "Can, cylindrical"),
    XCY("XCY", "Cylinder"),
    XCZ("XCZ", "Canvas"),
    XDA("XDA", "Crate, multiple layer, plastic"),
    XDB("XDB", "Crate, multiple layer, wooden"),
    XDC("XDC", "Crate, multiple layer, cardboard"),
    XDG("XDG", "Cage, Commonwealth Handling Equipment Pool  (CHEP)"),
    XDH("XDH", "Box, Commonwealth Handling Equipment Pool (CHEP), Eurobox"),
    XDI("XDI", "Drum, iron"),
    XDJ("XDJ", "Demijohn, non-protected"),
    XDK("XDK", "Crate, bulk, cardboard"),
    XDL("XDL", "Crate, bulk, plastic"),
    XDM("XDM", "Crate, bulk, wooden"),
    XDN("XDN", "Dispenser"),
    XDP("XDP", "Demijohn, protected"),
    XDR("XDR", "Drum"),
    XDS("XDS", "Tray, one layer no cover, plastic"),
    XDT("XDT", "Tray, one layer no cover, wooden"),
    XDU("XDU", "Tray, one layer no cover, polystyrene"),
    XDV("XDV", "Tray, one layer no cover, cardboard"),
    XDW("XDW", "Tray, two layers no cover, plastic tray"),
    XDX("XDX", "Tray, two layers no cover, wooden"),
    XDY("XDY", "Tray, two layers no cover, cardboard"),
    XEC("XEC", "Bag, plastic"),
    XED("XED", "Case, with pallet base"),
    XEE("XEE", "Case, with pallet base, wooden"),
    XEF("XEF", "Case, with pallet base, cardboard"),
    XEG("XEG", "Case, with pallet base, plastic"),
    XEH("XEH", "Case, with pallet base, metal"),
    XEI("XEI", "Case, isothermic"),
    XEN("XEN", "Envelope"),
    XFB("XFB", "Flexibag"),
    XFC("XFC", "Crate, fruit"),
    XFD("XFD", "Crate, framed"),
    XFE("XFE", "Flexitank"),
    XFI("XFI", "Firkin"),
    XFL("XFL", "Flask"),
    XFO("XFO", "Footlocker"),
    XFP("XFP", "Filmpack"),
    XFR("XFR", "Frame"),
    XFT("XFT", "Foodtainer"),
    XFW("XFW", "Cart, flatbed"),
    XFX("XFX", "Bag, flexible container"),
    XGB("XGB", "Bottle, gas"),
    XGI("XGI", "Girder"),
    XGL("XGL", "Container, gallon"),
    XGR("XGR", "Receptacle, glass"),
    XGU("XGU", "Tray, containing horizontally stacked flat items"),
    XGY("XGY", "Bag, gunny"),
    XGZ("XGZ", "Girders, in bundle/bunch/truss"),
    XHA("XHA", "Basket, with handle, plastic"),
    XHB("XHB", "Basket, with handle, wooden"),
    XHC("XHC", "Basket, with handle, cardboard"),
    XHG("XHG", "Hogshead"),
    XHN("XHN", "Hanger"),
    XHR("XHR", "Hamper"),
    XIA("XIA", "Package, display, wooden"),
    XIB("XIB", "Package, display, cardboard"),
    XIC("XIC", "Package, display, plastic"),
    XID("XID", "Package, display, metal"),
    XIE("XIE", "Package, show"),
    XIF("XIF", "Package, flow"),
    XIG("XIG", "Package, paper wrapped"),
    XIH("XIH", "Drum, plastic"),
    XIK("XIK", "Package, cardboard, with bottle grip-holes"),
    XIL("XIL", "Tray, rigid, lidded stackable (CEN TS 14482:2002)"),
    XIN("XIN", "Ingot"),
    XIZ("XIZ", "Ingots, in bundle/bunch/truss"),
    XJB("XJB", "Bag, jumbo"),
    XJC("XJC", "Jerrican, rectangular"),
    XJG("XJG", "Jug"),
    XJR("XJR", "Jar"),
    XJT("XJT", "Jutebag"),
    XJY("XJY", "Jerrican, cylindrical"),
    XKG("XKG", "Keg"),
    XKI("XKI", "Kit"),
    XLE("XLE", "Luggage"),
    XLG("XLG", "Log"),
    XLT("XLT", "Lot"),
    XLU("XLU", "Lug"),
    XLV("XLV", "Liftvan"),
    XLZ("XLZ", "Logs, in bundle/bunch/truss"),
    XMA("XMA", "Crate, metal"),
    XMB("XMB", "Bag, multiply"),
    XMC("XMC", "Crate, milk"),
    XME("XME", "Container, metal"),
    XMR("XMR", "Receptacle, metal"),
    XMS("XMS", "Sack, multi-wall"),
    XMT("XMT", "Mat"),
    XMW("XMW", "Receptacle, plastic wrapped"),
    XMX("XMX", "Matchbox"),
    XNA("XNA", "Not available"),
    XNE("XNE", "Unpacked or unpackaged"),
    XNF("XNF", "Unpacked or unpackaged, single unit"),
    XNG("XNG", "Unpacked or unpackaged, multiple units"),
    XNS("XNS", "Nest"),
    XNT("XNT", "Net"),
    XNU("XNU", "Net, tube, plastic"),
    XNV("XNV", "Net, tube, textile"),
    XOA("XOA", "Pallet, CHEP 40 cm x 60 cm"),
    XOB("XOB", "Pallet, CHEP 80 cm x 120 cm"),
    XOC("XOC", "Pallet, CHEP 100 cm x 120 cm"),
    XOD("XOD", "Pallet, AS 4068-1993"),
    XOE("XOE", "Pallet, ISO T11"),
    XOF("XOF", "Platform, unspecified weight or dimension"),
    XOK("XOK", "Block"),
    XOT("XOT", "Octabin"),
    XOU("XOU", "Container, outer"),
    XP2("XP2", "Pan"),
    XPA("XPA", "Packet"),
    XPB("XPB", "Pallet, box Combined open-ended box and pallet"),
    XPC("XPC", "Parcel"),
    XPD("XPD", "Pallet, modular, collars 80cms * 100cms"),
    XPE("XPE", "Pallet, modular, collars 80cms * 120cms"),
    XPF("XPF", "Pen"),
    XPG("XPG", "Plate"),
    XPH("XPH", "Pitcher"),
    XPI("XPI", "Pipe"),
    XPJ("XPJ", "Punnet"),
    XPK("XPK", "Package"),
    XPL("XPL", "Pail"),
    XPN("XPN", "Plank"),
    XPO("XPO", "Pouch"),
    XPP("XPP", "Piece"),
    XPR("XPR", "Receptacle, plastic"),
    XPT("XPT", "Pot"),
    XPU("XPU", "Tray"),
    XPV("XPV", "Pipes, in bundle/bunch/truss"),
    XPX("XPX", "Pallet"),
    XPY("XPY", "Plates, in bundle/bunch/truss"),
    XPZ("XPZ", "Planks, in bundle/bunch/truss"),
    XQA("XQA", "Drum, steel, non-removable head"),
    XQB("XQB", "Drum, steel, removable head"),
    XQC("XQC", "Drum, aluminium, non-removable head"),
    XQD("XQD", "Drum, aluminium, removable head"),
    XQF("XQF", "Drum, plastic, non-removable head"),
    XQG("XQG", "Drum, plastic, removable head"),
    XQH("XQH", "Barrel, wooden, bung type"),
    XQJ("XQJ", "Barrel, wooden, removable head"),
    XQK("XQK", "Jerrican, steel, non-removable head"),
    XQL("XQL", "Jerrican, steel, removable head"),
    XQM("XQM", "Jerrican, plastic, non-removable head"),
    XQN("XQN", "Jerrican, plastic, removable head"),
    XQP("XQP", "Box, wooden, natural wood, ordinary"),
    XQQ("XQQ", "Box, wooden, natural wood, with sift proof walls"),
    XQR("XQR", "Box, plastic, expanded"),
    XQS("XQS", "Box, plastic, solid"),
    XRD("XRD", "Rod"),
    XRG("XRG", "Ring"),
    XRJ("XRJ", "Rack, clothing hanger"),
    XRK("XRK", "Rack"),
    XRL("XRL", "Reel"),
    XRO("XRO", "Roll"),
    XRT("XRT", "Rednet"),
    XRZ("XRZ", "Rods, in bundle/bunch/truss"),
    XSA("XSA", "Sack"),
    XSB("XSB", "Slab"),
    XSC("XSC", "Crate, shallow"),
    XSD("XSD", "Spindle"),
    XSE("XSE", "Sea-chest"),
    XSH("XSH", "Sachet"),
    XSI("XSI", "Skid"),
    XSK("XSK", "Case, skeleton"),
    XSL("XSL", "Slipsheet"),
    XSM("XSM", "Sheetmetal"),
    XSO("XSO", "Spool"),
    XSP("XSP", "Sheet, plastic wrapping"),
    XSS("XSS", "Case, steel"),
    XST("XST", "Sheet"),
    XSU("XSU", "Suitcase"),
    XSV("XSV", "Envelope, steel"),
    XSW("XSW", "Shrinkwrapped"),
    XSY("XSY", "Sleeve"),
    XSZ("XSZ", "Sheets, in bundle/bunch/truss"),
    XT1("XT1", "Tablet"),
    XTB("XTB", "Tub"),
    XTC("XTC", "Tea-chest"),
    XTD("XTD", "Tube, collapsible"),
    XTE("XTE", "Tyre"),
    XTG("XTG", "Tank container, generic"),
    XTI("XTI", "Tierce"),
    XTK("XTK", "Tank, rectangular"),
    XTL("XTL", "Tub, with lid"),
    XTN("XTN", "Tin"),
    XTO("XTO", "Tun"),
    XTR("XTR", "Trunk"),
    XTS("XTS", "Truss"),
    XTT("XTT", "Bag, tote"),
    XTU("XTU", "Tube"),
    XTV("XTV", "Tube, with nozzle"),
    XTW("XTW", "Pallet, triwall"),
    XTY("XTY", "Tank, cylindrical"),
    XTZ("XTZ", "Tubes, in bundle/bunch/truss"),
    XUC("XUC", "Uncaged"),
    XUN("XUN", "Unit"),
    XVA("XVA", "Vat"),
    XVG("XVG", "Bulk, gas (at 1031 mbar and 15 °C)"),
    XVI("XVI", "Vial"),
    XVK("XVK", "Vanpack"),
    XVL("XVL", "Bulk, liquid"),
    XVN("XVN", "Vehicle"),
    XVO("XVO", "Bulk, solid, large particles (“nodules”)"),
    XVP("XVP", "Vacuum-packed"),
    XVQ("XVQ", "Bulk, liquefied gas (at abnormal temperature/pressure)"),
    XVR("XVR", "Bulk, solid, granular particles (“grains”)"),
    XVS("XVS", "Bulk, scrap metal"),
    XVY("XVY", "Bulk, solid, fine particles (“powders”)"),
    XWA("XWA", "Intermediate bulk container"),
    XWB("XWB", "Wickerbottle"),
    XWC("XWC", "Intermediate bulk container, steel"),
    XWD("XWD", "Intermediate bulk container, aluminium"),
    XWF("XWF", "Intermediate bulk container, metal"),
    XWG("XWG", "Intermediate bulk container, steel, pressurised > 10 kpa"),
    XWH("XWH", "Intermediate bulk container, aluminium, pressurised > 10 kpa"),
    XWJ("XWJ", "Intermediate bulk container, metal, pressure 10 kpa"),
    XWK("XWK", "Intermediate bulk container, steel, liquid"),
    XWL("XWL", "Intermediate bulk container, aluminium, liquid"),
    XWM("XWM", "Intermediate bulk container, metal, liquid"),
    XWN("XWN", "Intermediate bulk container, woven plastic, without coat/liner"),
    XWP("XWP", "Intermediate bulk container, woven plastic, coated"),
    XWQ("XWQ", "Intermediate bulk container, woven plastic, with liner"),
    XWR("XWR", "Intermediate bulk container, woven plastic, coated and liner"),
    XWS("XWS", "Intermediate bulk container, plastic film"),
    XWT("XWT", "Intermediate bulk container, textile with out coat/liner"),
    XWU("XWU", "Intermediate bulk container, natural wood, with inner liner"),
    XWV("XWV", "Intermediate bulk container, textile, coated"),
    XWW("XWW", "Intermediate bulk container, textile, with liner"),
    XWX("XWX", "Intermediate bulk container, textile, coated and liner"),
    XWY("XWY", "Intermediate bulk container, plywood, with inner liner"),
    XWZ("XWZ", "Intermediate bulk container, reconstituted wood, with inner liner"),
    XXA("XXA", "Bag, woven plastic, without inner coat/liner"),
    XXB("XXB", "Bag, woven plastic, sift proof"),
    XXC("XXC", "Bag, woven plastic, water resistant"),
    XXD("XXD", "Bag, plastics film"),
    XXF("XXF", "Bag, textile, without inner coat/liner"),
    XXG("XXG", "Bag, textile, sift proof"),
    XXH("XXH", "Bag, textile, water resistant"),
    XXJ("XXJ", "Bag, paper, multi-wall"),
    XXK("XXK", "Bag, paper, multi-wall, water resistant"),
    XYA("XYA", "Composite packaging, plastic receptacle in steel drum"),
    XYB("XYB", "Composite packaging, plastic receptacle in steel crate box"),
    XYC("XYC", "Composite packaging, plastic receptacle in aluminium drum"),
    XYD("XYD", "Composite packaging, plastic receptacle in aluminium crate"),
    XYF("XYF", "Composite packaging, plastic receptacle in wooden box"),
    XYG("XYG", "Composite packaging, plastic receptacle in plywood drum"),
    XYH("XYH", "Composite packaging, plastic receptacle in plywood box"),
    XYJ("XYJ", "Composite packaging, plastic receptacle in fibre drum"),
    XYK("XYK", "Composite packaging, plastic receptacle in fibreboard box"),
    XYL("XYL", "Composite packaging, plastic receptacle in plastic drum"),
    XYM("XYM", "Composite packaging, plastic receptacle in solid plastic box"),
    XYN("XYN", "Composite packaging, glass receptacle in steel drum"),
    XYP("XYP", "Composite packaging, glass receptacle in steel crate box"),
    XYQ("XYQ", "Composite packaging, glass receptacle in aluminium drum"),
    XYR("XYR", "Composite packaging, glass receptacle in aluminium crate"),
    XYS("XYS", "Composite packaging, glass receptacle in wooden box"),
    XYT("XYT", "Composite packaging, glass receptacle in plywood drum"),
    XYV("XYV", "Composite packaging, glass receptacle in wickerwork hamper"),
    XYW("XYW", "Composite packaging, glass receptacle in fibre drum"),
    XYX("XYX", "Composite packaging, glass receptacle in fibreboard box"),
    XYY("XYY", "Composite packaging, glass receptacle in expandable plastic pack"),
    XYZ("XYZ", "Composite packaging, glass receptacle in solid plastic pack"),
    XZA("XZA", "Intermediate bulk container, paper, multi-wall"),
    XZB("XZB", "Bag, large"),
    XZC("XZC", "Intermediate bulk container, paper, multi-wall, water resistant"),
    XZD("XZD", "Intermediate bulk container, rigid plastic, with structural equipment, solids"),
    XZF("XZF", "Intermediate bulk container, rigid plastic, freestanding, solids"),
    XZG("XZG", "Intermediate bulk container, rigid plastic, with structural equipment, pressurised"),
    XZH("XZH", "Intermediate bulk container, rigid plastic, freestanding, pressurised"),
    XZJ("XZJ", "Intermediate bulk container, rigid plastic, with structural equipment, liquids"),
    XZK("XZK", "Intermediate bulk container, rigid plastic, freestanding, liquids"),
    XZL("XZL", "Intermediate bulk container, composite, rigid plastic, solids"),
    XZM("XZM", "Intermediate bulk container, composite, flexible plastic, solids"),
    XZN("XZN", "Intermediate bulk container, composite, rigid plastic, pressurised"),
    XZP("XZP", "Intermediate bulk container, composite, flexible plastic, pressurised"),
    XZQ("XZQ", "Intermediate bulk container, composite, rigid plastic, liquids"),
    XZR("XZR", "Intermediate bulk container, composite, flexible plastic, liquids"),
    XZS("XZS", "Intermediate bulk container, composite"),
    XZT("XZT", "Intermediate bulk container, fibreboard"),
    XZU("XZU", "Intermediate bulk container, flexible"),
    XZV("XZV", "Intermediate bulk container, metal, other than steel"),
    XZW("XZW", "Intermediate bulk container, natural wood"),
    XZX("XZX", "Intermediate bulk container, plywood"),
    XZY("XZY", "Intermediate bulk container, reconstituted wood"),
    XZZ("XZZ", "Mutually defined"),
    YDK("YDK", "Square yard"),
    YDQ("YDQ", "Cubic yard"),
    YRD("YRD", "Yard"),
    Z11("Z11", "Hanging container"),
    ZP("ZP", "Page"),
    ZZ("ZZ", "Mutually defined"),
    ;

    private final String name;
    private final String code;

    MeasurementUnitCode(String code, String name) {
        this.code = code;
        this.name = name;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public String getCode() {
        return code;
    }

}
