<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.up2jakarta</groupId>
        <artifactId>up2-divers</artifactId>
        <version>1.7.2</version>
    </parent>

    <artifactId>up2job-core</artifactId>
    <name>Up2Job :: Core</name>
    <description>Spring Batch Extensions</description>
    <url>https://github.com/up2jakarta/up2-divers/tree/master/up2job-core</url>

    <scm>
        <connection>scm:git:git://github.com/up2jakarta/up2-divers.git</connection>
        <developerConnection>scm:git:ssh://github.com/up2jakarta/up2-divers.git</developerConnection>
        <url>https://github.com/up2jakarta/up2-divers.git</url>
    </scm>

    <dependencies>
        <!-- Required API Dependencies -->
        <dependency>
            <groupId>io.github.up2jakarta</groupId>
            <artifactId>up2xml-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.batch</groupId>
            <artifactId>spring-batch-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <!-- Test dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.batch</groupId>
            <artifactId>spring-batch-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.up2jakarta</groupId>
            <artifactId>up2csv-format</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Optional dependencies -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <optional>true</optional>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
