<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.up2jakarta</groupId>
        <artifactId>up2-divers</artifactId>
        <version>1.4.7</version>
    </parent>

    <artifactId>up2job-core</artifactId>
    <name>Up2Job :: Core</name>
    <description>Spring Batch Extensions</description>
    <url>https://github.com/up2jakarta/up2-divers/tree/master/up2job-core</url>

    <developers>
        <developer>
            <name>A.ABBESSI</name>
            <email>up2Abbessi[at]gmail.com</email>
            <roles>
                <role>Software engineer</role>
                <role>Developer Lead</role>
                <role>Technical Lead</role>
                <role>Application Architect</role>
            </roles>
            <url>https://up2jakarta.github.io/</url>
        </developer>
    </developers>
    <dependencies>
        <dependency>
            <groupId>io.github.up2jakarta</groupId>
            <artifactId>up2csv-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.batch</groupId>
            <artifactId>spring-batch-core</artifactId>
        </dependency>
    </dependencies>

</project>
